"""Root-authored full text and profile corrections for seven audited teams."""
import copy,json
from pathlib import Path
ROOT=Path(__file__).parent
def read(n):return json.loads((ROOT/n).read_text(encoding='utf8'))
a=read('inventory/critic-full-team-audit-b.json');q=a['findings'];c=read('inventory/current-rule-base-cards.json');out=[]
sources={s['team']:s for s in a['sources']}
def p(n):
 x=q[n];id=x['exactID'];v=c[id];s=sources[x['team']]
 t={'id':id,'expectedTitle':v['titleEnglish'],'team':x['team'],'source':{'officialPdf':s['officialPdf'],'date':s['officialCatalogDate'],'wahapedia':s['wahaPage'],'checkedOn':'2026-10-05','evidence':x['evidence']}};out.append(t);return t
def b(n,heading):return next(x for x in c[q[n]['exactID']].get('blocks',[]) if x.get('headingEnglish')==heading)
def text(n,heading,ru,en=None,append=False,ruHeading=None):
 t=p(n);u={'heading':heading,'russian':ru,'english':en or q[n]['currentfullrule'],'proseTitles':[heading.split(' ·')[0].split(' (')[0].split(':')[0]]}
 if append:u.update(append=True,headingRussian=ruHeading)
 t['blocks']=[u];return t
def replace(n,heading,ruOld,ruNew,enOld,enNew):
 v=b(n,heading);assert ruOld in v['russian'],(n,ruOld);assert enOld in v['english'],(n,enOld)
 return text(n,heading,v['russian'].replace(ruOld,ruNew),v['english'].replace(enOld,enNew))
def extend(n,heading,ru,en):
 v=b(n,heading);return text(n,heading,v['russian']+'\n'+ru,v['english']+' '+en)

text(0,'Harrowing Whispers','Когда противник собирается активировать вражеского оперативника в пределах 6 дюймов от этого оперативника, можно бросить один D6. Нельзя делать этот бросок, если в этом раунде вы уже прерывали активацию выбранного врага этим правилом или правилом «Зловещий прицел» (Haunting Focus) оперативника DIRGEMAW. Если результат D6 выше APL выбранного врага, противник не может активировать его в эту активацию. Если нет других врагов, которых можно активировать, правило не действует.')
text(1,'Haunting Focus: STRATEGIC GAMBIT','Выберите одного вражеского оперативника: до шага готовности (Ready) следующей фазы стратегии он получает ваш жетон зловещего прицела (Haunting Focus). Когда противник в следующий раз собирается активировать врага с этим жетоном, если этот оперативник готов, можно сначала активировать его. Нельзя делать это, если в этом раунде вы уже бросали кубик для предотвращения активации выбранного врага правилом «Мучительные шёпоты» (Harrowing Whispers) оперативника NIGHTFIEND.\nВ эту активацию этот оперативник должен сразиться с выбранным врагом или выстрелить по нему; до этого он не может сражаться или стрелять по другим врагам. Если выполнить это невозможно, активация отменяется. После его активации противник активирует выбранного врага, если возможно, либо другого врага, если выбранного активировать нельзя.',en='Select one enemy operative. Until the Ready step of the next Strategy phase, it gains your Haunting Focus token. '+q[1]['currentfullrule'])
text(2,'Pareidolic Projection (1AP)','Выберите одного врага, который является допустимой целью для этого оперативника или находится в тени (WITHIN SHADOW). До начала следующей активации этого оперативника, его выведения из строя или повторного выполнения им этого действия — что наступит раньше — ухудшите HIT оружия выбранного врага на 1 и уменьшите его MOVE на 2 дюйма. Эффект не суммируется с ранением.\nЭто действие нельзя выполнять в дистанции контроля врага, если только выбранный враг не является единственным врагом в дистанции контроля этого оперативника.',en=q[2]['currentfullrule'].replace(' The APL clause is deleted.',''))
for n in [3,12]:extend(n,'Rule','После результата 4+ это правило нельзя применять повторно в том же раунде.','If any result is a 4+, you cannot use this rule again during this turning point.')
replace(4,'Quicksilver Strike','прервать его активацию или ответное действие и применить','прервать последовательность игры и применить','interrupt that activation/counteraction to use','interrupt to use')
extend(5,'Rule','Если это действие «Стрелять» (Shoot), заменяющий оперативник получает укрытие (Cover) или заслонение (Obscured) только если их имела исходная цель.','If it is the Shoot action, that other operative is only in cover or obscured if the original target was.')
for n in [6,7]:p(n)['stats']={'Wounds':9}
text(9,'Cunning','На шаге гамбитов каждой фазы стратегии, если этот оперативник находится в зоне боя и вы пасуете при первой возможности, получите 1 CP. При проверке этого условия игнорируйте стратегические гамбиты (STRATEGIC GAMBIT) набора миссий, если они есть.')
text(10,'Torturous Vision','Один раз в каждую свою активацию, когда этот оперативник выполняет действие «Сражаться» (Fight) или «Стрелять» (Shoot), если у него нет ваших жетонов боли (Pain), он может получить один такой жетон при выборе допустимой цели стрельбы или врага для боя.',append=True,ruHeading='Мучительное видение')
replace(11,'Combat Drugs','«Адреналайт» (Adrenalight): стратегический гамбит (Strategic Gambit). Выберите','«Адреналайт» (Adrenalight): на шаге готовности (Ready) каждой фазы стратегии можно выбрать','Adrenalight: STRATEGIC GAMBIT. Select','Adrenalight: In the Ready step of each Strategy phase, you can select')
text(13,'Crimson Duellist','Этот оперативник может выполнить два действия «Сражаться» (Fight) в свою активацию.')
replace(14,'Stimulated Senses','перебросьте один свой кубик.','выберите одно значение результата, например 2, и перебросьте любое количество своих кубиков с этим результатом.','You can re-roll one of your dice.','You can re-roll any of your dice results of one result (e.g. results of 2).')
replace(15,'Power from Pain','его можно использовать вдобавок к другим усилениям.','его можно использовать один раз за активацию или контратаку дополнительно к одному другому усилению.','which can be used in addition to other invigorations.','which can be used once per activation or counteraction in addition to another invigoration.')
replace(16,'Rule','тяжёлый террейн','тяжёлый (Heavy) или лёгкий (Light) террейн','if Heavy terrain is intervening','if Heavy or Light terrain is intervening')
replace(17,'Roster restrictions','более 6 таких','более 7 таких','more than 6','more than 7')
for n in range(18,24):text(n,'Control Protocol','Можно применить тактическую уловку «Переопределение команд» (Command Override) за 0 CP, если указанный в ней дружественный оперативник Охотничьей клады (HUNTER CLADE) видим этому оперативнику.',append=True,ruHeading='Протокол управления')
for n in range(24,40):p(n)['keyword']=['IMPERIUM','ИМПЕРИУМ (IMPERIUM)']
replace(40,'Rule',' Нанесите дружественному оперативнику D3+1 урона.','',' Inflict D3+1 damage on that friendly operative.','')
replace(41,'Rule · continuation','во время одного подъёма','во время одного подъёма вверх','during one climb.','during one climb up.')
replace(42,'Whip Into Frenzy · 1AP','увеличьте его Перемещение (Move) на 1 дюйм','увеличьте его APL на 1 и MOVE на 1 дюйм','add 1" to its Move stat','add 1 to its APL stat, add 1" to its Move stat')
medic=c['7b57d5bb83d8aba7']['blocks'][0]
text(43,'Medic',medic['russian'].replace('DEATH KORPS','Новициаток (NOVITIATE)'),medic['english'].replace('DEATH KORPS','NOVITIATE'))
replace(44,'Chirurgeon’s Tools · 1AP','восстанавливает 2D3 потерянные раны','восстанавливает до 2D3 потерянных ран','regain 2D3 lost wounds','regain up to 2D3 lost wounds')
replace(45,'Rule','оспаривающей маркер цели','оспаривающей маркер цели или один ваш маркер миссии','contests an objective marker','contests an objective marker or one of your mission markers')
out[-1]['blocks'][0]['russian']=out[-1]['blocks'][0]['russian'].replace('получает от неё ответный удар','отвечает на её атаку')
extend(46,'Rule','Эта уловка также не действует, если выбранный оперативник был выведен из строя в ходе этого действия.','This ploy also has no effect if that friendly operative was incapacitated during that action.')
replace(47,'Rule','выведен из строя. За','выведен из строя, до его удаления из зоны боя. За','is incapacitated. For','is incapacitated, before it is removed from the killzone. For')
replace(48,'Rule','у вас остаются критические успехи','вы наносите урон хотя бы одним критическим успехом','you retain any critical successes','you inflict damage with any critical successes')
for n,name,ru in [(49,'Novitiate Hospitaller','Госпиталерка Новициаток'),(50,'Novitiate Hospitaller','Госпиталерка Новициаток'),(51,'Novitiate Duellist','Дуэлянтка Новициаток')]:t=p(n);t.update(titleEnglish=name,titleRussian=ru+' ('+name+')')
extend(52,'Grudge','Это включает обычные успехи, сохранённые по правилу «Точное» (Accurate).','This includes normal successes retained as a result of the Accurate weapon rule.')
extend(53,'Rule','Можно игнорировать любые изменения характеристик оружия выбранного оперативника от ранения (Injured).','You can ignore any changes to that operative’s weapon stats from being injured.')
text(54,'Well Supplied','Можно выбрать один дополнительный вариант снаряжения. На шаге готовности первой фазы стратегии получите 1 дополнительный CP.')
extend(55,'Rule','Если у оружия ближнего боя уже ATK 4, вместо увеличения ATK оно получает правило «Сбалансированное» (Balanced).','If the melee weapon already has an Atk stat of 4, it has the Balanced weapon rule.')
extend(56,'Rule','Изменение HIT можно применить или убрать во время действия. Это имеет приоритет над основными правилами.','This Hit stat change can be applied or removed during an action; this takes precedence over the core rules.')
text(57,'Rule','Когда по дружественному оперативнику Харткин-спасателей (HEARTHKYN SALVAGER) стреляют, на шаге броска кубиков защиты, если у вас выпал один успех или меньше, включая перебросы, можно сохранить один провал как обычный успех вместо сброса.',en='Whenever an operative is shooting a friendly HEARTHKYN SALVAGER operative, in the Roll Defence Dice step, if you rolled one or less successes (including any re-rolls), you can retain one of your fails as a normal success instead of discarding it.')
text(58,'Rule','В каждую активацию каждого дружественного оперативника Харткин-спасателей выберите один эффект:\n• При подъёме вверх (Climb Up) считайте вертикальную дистанцию равной 2 дюймам независимо от фактического расстояния.\n• При спуске (Drop) игнорируйте вертикальную дистанцию.')
eye=c['446929d4d175c54c']['blocks'][0]
for n,id,append in [(59,'0acb185d702bac2b',True),(59,'446929d4d175c54c',False)]:
 t=text(n,'Eye of the Ancestors',eye['russian'].replace('СТРАТЕГИЧЕСКИЙ МАНЁВР (STRATEGIC GAMBIT).','Стратегический гамбит (STRATEGIC GAMBIT), если этот оперативник находится в зоне боя.'),eye['english'].replace('STRATEGIC GAMBIT.','STRATEGIC GAMBIT if this operative is in the killzone.'),append=append,ruHeading='Взор предков');t['id']=id;t['expectedTitle']=c[id]['titleEnglish']
extend(60,'Brawler','Если кубик атаки наносит этому оперативнику обычный урон (Normal Dmg) 4 или больше, уменьшите этот урон на 1.','Whenever an attack dice inflicts Normal Dmg of 4 or more on this operative, subtract 1 from that inflicted damage.')
replace(61,'Signal · 1AP · SUPPORT','видимого этому оперативнику и находящегося в пределах 6 дюймов от него','находящегося в зоне боя','visible to and within 6" of this operative','in the killzone')
text(62,'Tactician','Стратегический гамбит (STRATEGIC GAMBIT), если этот оперативник находится в зоне боя. Разместите свой маркер атаки (Attack) или защиты (Defence) в зоне боя. Когда дружественный Харткин-спасатель стреляет, сражается или отвечает в ближнем бою против врага в пределах 3 дюймов от маркера атаки, его оружие получает «Сбалансированное» (Balanced). Когда враг стреляет по дружественному Харткин-спасателю в пределах 3 дюймов от маркера защиты, можно перебросить один свой защитный кубик. Уберите маркер на шаге готовности следующей фазы стратегии.',en='STRATEGIC GAMBIT if this operative is in the killzone. Place either your Attack or Defence marker in the killzone. Whenever a friendly HEARTHKYN SALVAGER operative is shooting against, fighting against or retaliating against an enemy operative within 3" of your Attack marker, its weapons have Balanced. Whenever an enemy operative is shooting a friendly HEARTHKYN SALVAGER operative within 3" of your Defence marker, you can re-roll one defence dice. In the Ready step of the next Strategy phase, remove that marker.')
text(63,'Weavefield Crest','Один раз за бой, когда кубик атаки наносит этому оперативнику обычный урон (Normal Dmg), можно проигнорировать этот урон.')
replace(65,'Poison','оперативник, против которого использовали это оружие, получает','оперативник, против которого использовали это оружие, кроме дружественного чумного десантника (PLAGUE MARINE), получает','the operative this weapon is being used against gains','the operative this weapon is being used against (excluding friendly PLAGUE MARINE operatives) gains')
text(66,'Rule','Когда вражеский оперативник активируется в пределах 3 дюймов от дружественного чумного десантника (PLAGUE MARINE):\n• Если у врага ещё нет вашего жетона яда (Poison), бросьте D3: на 3 враг получает один такой жетон.\n• Если у врага уже есть ваш жетон яда, нанесите ему D3 урона вместо обычного 1.')
replace(67,'Rule','выведен из строя. Каждый','выведен из строя, до его удаления из зоны боя. Каждый','is incapacitated. Each','is incapacitated, before it is removed from the killzone. Each')
replace(68,'Rule','Каждый такой результат считается провалом, и противник не может перебросить соответствующий кубик.','Каждый такой результат нельзя сохранить как успех, и его нельзя перебросить.','treat that result as a fail, and they cannot re-roll it','that result cannot be retained as a success and cannot be re-rolled')
replace(69,'Rule','оперативник в пределах 3 дюймов от него получает','оперативник в пределах 3 дюймов от него либо видимый ему и в пределах 7 дюймов от него получает','operative within 3 inches of that operative gains','operative within 3 inches of that operative, or visible to and within 7 inches of it, gains')
text(70,'Rule','Уменьшите MOVE врага на 2 дюйма и ухудшите HIT его оружия на 1, когда выполняется хотя бы одно условие:\n• У врага есть ваш жетон яда (Poison), он в пределах 3 дюймов от дружественного чумного десантника (PLAGUE MARINE), и хотя бы один из них видит другого.\n• Враг в пределах 3 дюймов от дружественного Носителя иконы (ICON BEARER) Чумных десантников, и хотя бы один из них видит другого.\nЭффект не суммируется с ранением.',en='Subtract 2" from an enemy operative’s Move and worsen its weapons’ Hit by 1 (not cumulative with being injured) whenever it has one of your Poison tokens and is visible to (or vice versa) and within 3" of a friendly PLAGUE MARINE, or is visible to (or vice versa) and within 3" of a friendly PLAGUE MARINE ICON BEARER.')
replace(71,'Rule','полностью находится в пределах 3 дюймов от этого маркера','целиком находится в пределах 1 дюйма от этого маркера','wholly within 3" of that marker','wholly within 1" of that marker')
for n in [72,73,74]:text(n,'Toxic','Когда этот оперативник использует это оружие против врага, у которого в начале этого действия уже был ваш жетон яда (Poison), увеличьте обе характеристики DMG этого оружия на 1.',en='Whenever this operative is using this weapon against an enemy operative that had one of your Poison tokens at the start of that action, add 1 to both Dmg stats of this weapon.')
text(75,'Grandfather’s Blessing','Когда враг с вашим жетоном яда (Poison) теряет одну или больше ран в пределах 7 дюймов от этого оперативника, этот оперативник восстанавливает до такого же числа потерянных ран. За раунд можно восстановить не больше 3 ран; эффект действует, только если этот оперативник не выведен из строя.')
for n in [76,77]:p(n)['weapons']=[{'name':'Bolt pistol','append':True,'type':'R','russian':'Болт-пистолет (Bolt pistol)','atk':4,'hit':'3+','dmg':'3/4','wrEnglish':'Range 8"','wrRussian':'Дальность 8 дюймов (Range 8″)'}]
(ROOT/'ru-current-updates-b.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
print(json.dumps({'patches':len(out),'deferred':['New Plague Marine roster card'],'sourceConflictsKeptOfficial':[8,64]}))
