"""Root effective rules for audit D, preserving non-updated clauses."""
import json,re
from pathlib import Path
R=Path(__file__).parent
def read(n):return json.loads((R/n).read_text(encoding='utf8'))
a=read('inventory/critic-full-team-audit-d.json');q=a['findings'];c=read('inventory/current-rule-base-cards.json');sources={x['team']:x for x in a['sources']['teams']};out=[]
def patch(n,id=None):
 x=q[n];id=id or x['localIds'][0];s=sources[x['team']]
 p={'id':id,'expectedTitle':c[id]['titleEnglish'],'team':x['team'],'source':{'officialPdf':s['officialPdfUrl'],'date':s['officialCatalogLastUpdated'],'wahapedia':s['wahapediaUrl'],'checkedOn':'2026-10-05','evidence':x['evidence']}};out.append(p);return p
def old(n,h,id=None):return next(b for b in c[id or q[n]['localIds'][0]].get('blocks',[]) if b.get('headingEnglish')==h)
def body(n,h,ru,en,id=None,append=False,hr=None):
 p=patch(n,id);u={'heading':h,'russian':ru,'english':en,'proseTitles':[h.split(' ·')[0].split(' (')[0]]}
 if append:u.update(append=True,headingRussian=hr or h)
 p['blocks']=[u];return u
def edit(n,h,ro,rn,eo,en,id=None):
 b=old(n,h,id);assert ro in b['russian'] and eo in b['english'],(n,h,ro,eo)
 return body(n,h,b['russian'].replace(ro,rn),b['english'].replace(eo,en),id)
def extra(n,h,ru,en,id=None):
 b=old(n,h,id);return body(n,h,b['russian']+'\n'+ru,b['english']+' '+en,id)
u=edit(0,'Frenzy','и миссионные действия','и миссионные действия','or mission actions','or mission actions')
u['russian']=u['russian'].replace('; при определении контроля над маркерами','; он не может выполнять уникальные действия, кроме «Размашистого удара» (Sweeping Blow); при определении контроля над маркерами и областями зоны боя')
u['english']=u['english'].replace('For the purpose of determining control of markers','It cannot perform unique actions except Sweeping Blow. For the purpose of determining control of markers and areas of the killzone')
extra(0,'Incapacitation while Frenzied','Дополнительное условие: вражеский оперативник выполняет «Стрельбу» (Shoot) по нему и наносит ему обычный урон (Normal Dmg) двумя или более кубиками атаки.','An additional condition: an enemy operative performs Shoot against it and inflicts Normal Dmg with two or more attack dice.',q[0]['localIds'][1])
b=old(1,'Rule');body(1,'Rule',b['russian'],b['english']) # Fail-to-normal clause is struck in the current PDF.
b=old(3,'Incite Fury (1AP) · SUPPORT');u=body(3,'Incite Fury (1AP) · SUPPORT',b['russian'],b['english']);u.update(newHeadingEnglish='Incite Fury (1AP)',headingRussian='Разжечь ярость · 1 AP (Incite Fury)')
p=patch(4);p['weapons']=[{'name':'Vicious claws','hit':'4+'}]
extra(5,'Call the Attack · STRATEGIC GAMBIT','Этот стратегический гамбит можно применять только если у этого оперативника нет вашего жетона «Безумие» (Frenzy).','This STRATEGIC GAMBIT can only be used if this operative does not have one of your Frenzy tokens.')
edit(6,'Gong Knell (1AP)',' и игнорируйте правило оружия «Бронебойное» (Piercing)','',' and ignore the Piercing weapon rule','')
body(7,'Rules Commentary','Критический успех с DMG 0 не может вывести из строя оперативника с жетоном «Безумие» (Frenzy): критический урон должен быть нанесён.','A critical success with Critical Dmg 0 cannot incapacitate a Frenzied operative.',id='31b2ceff3bc7d1a0',append=True,hr='Разъяснение правил (Rules Commentary)')
edit(8,'Obsessive Bloodlust','Когда этот оперативник завершает','Один раз за раунд, когда этот оперативник завершает','Whenever this operative ends','Once per turning point, whenever this operative ends')
prey=old(9,'Prey');extra(9,'Drag',prey['russian'],prey['english']);p=patch(9);p['deleteBlocks']=['Prey'];p['weapons']=[{'name':'Fleshskewer (ranged)','atk':4,'hit':'3+','dmg':'4/5','wrEnglish':'Range 8", Piercing Crits 1, Stun, Drag*','wrRussian':'Дальность 8" (Range 8"), Бронебойное при критических успехах 1 (Piercing Crits 1), Оглушение (Stun), Притягивание (Drag)*'}]
body(9,'Gore-fuel · 1AP','Уменьшите уровень резервуара крови (GORE TANK) этого оперативника. Все профили его Плотесквера (Fleshskewer) получают «Сокрушительное» (Severe) до первого использования одного из этих профилей. Нельзя выполнять это действие в дистанции контроля врага либо с пустым резервуаром крови.','Decrease this operative’s GORE TANK. All profiles of its fleshskewer have Severe until it uses one of those profiles. This operative cannot perform this action while within enemy control range or if its GORE TANK is empty.',append=True,hr='Кровавое топливо · 1 AP (Gore-fuel)')
extra(10,'Rule','Если это оружие получило «Сбалансированное» (Balanced) или «Неумолимое» (Relentless) от «Усиленного насилия» (Enhanced Violence), оно сохраняет эти правила, когда считается стрелковым.','If it gained Balanced or Relentless from Enhanced Violence, it has those rules while treated as a ranged weapon.')
edit(11,'EFFECT','2D3','D3+1','2D3','D3+1')
extra(12,'WHEN','Только в свою активацию.','Only during its activation.')
edit(13,'Rule','(округляя вверх)','(округляя вверх, минимум до 2)','(rounding up)','(rounding up, to a minimum of 2)')
body(14,'Rooftop Stalker','Когда этот оперативник сражается в активацию, в которой спрыгнул с высоты (Vantage), находящейся хотя бы на 2 дюйма выше пола зоны боя, либо сражается с врагом на такой высоте, его оружие ближнего боя получает «Неумолимое» (Relentless).','Whenever this operative is fighting during an activation in which it dropped from Vantage terrain at least 2" above the killzone floor, or is fighting an enemy operative on Vantage terrain at least 2" above the killzone floor, its melee weapons have Relentless.')
edit(15,'Khorne’s Favour','активации этого оперативника, если','активации этого оперативника до или после выполнения им действия, если','activations, if','activations, before or after it performs an action, if')
edit(16,'Impending Apotheosis','наносит этому оперативнику урон','наносит этому оперативнику обычный урон (Normal Dmg)','inflicts damage on this operative','inflicts Normal Dmg on this operative')
edit(17,'Bleeding','наносит урон врагу, но','наносит урон врагу любым из профилей своих парных автопистолетов (Dual autopistols), но','inflicts damage on an enemy operative but','inflicts damage on an enemy operative with either profile of its dual autopistols but')
body(18,'Rules Commentary','Для «Усиленного насилия» (Enhanced Violence) проверяйте, полон ли резервуар крови (GORE TANK), после уменьшения его уровня для применяемой при действии сангвавиты (Sanguavitae).','For Enhanced Violence, check whether the GORE TANK is full after decreasing it for the Sanguavitae used for the action.',id='008a2b364f7e3c33',append=True,hr='Разъяснение правил (Rules Commentary)')
edit(19,'Archetype and operatives','Ещё 8 оперативников','Ещё 9 оперативников','8 VESPID STINGWING operatives selected','9 VESPID STINGWING operatives selected')
u=edit(20,'Rule','во время контрдействия (Counteract)','во время контрдействия (Counteract) или прерывания','while counteracting,','while counteracting or interrupting,');u['russian']=u['russian'].replace('обычный успех нанёс бы урон','кубик атаки нанёс бы обычный урон (Normal Dmg)');u['english']=u['english'].replace('a normal success would inflict damage','an attack dice would inflict Normal Dmg')
body(21,'Communion Helm','Один раз в каждую свою активацию выберите один вариант:\n• Потратить 1 очко Сопряжения (Communion) бесплатно.\n• Потратить 1 очко Сопряжения и выбрать другого дружественного Веспида-жалоносца (VESPID STINGWING) в пределах 3 дюймов: он немедленно бесплатно выполняет миссионное действие стоимостью 1 AP. Выбранный оперативник всё равно должен потратить требуемое для него очко Сопряжения; нельзя проигнорировать эту стоимость «Стимулятором конвергенции» (Convergence Stimulant).','Once during each activation select either: spend 1 Communion point for free; or spend 1 Communion point and select another friendly VESPID STINGWING within 3" to immediately perform a free 1AP mission action. That selected operative must still spend the normal Communion point and Convergence Stimulant cannot ignore that cost.')
extra(22,'Rule','Также улучшите HIT этих когтей на 1.','Also improve the Hit stat of those claws by 1.')
edit(23,'Skytorch','Оперативник может использовать это оружие только в активацию, в которой выполнил действие «Перемещение» (Reposition) с Полётом (FLY).','Это оружие можно использовать только во время «Атаки небесным факелом» (Skytorch Assault).','An operative can only use this weapon during an activation in which it performed the Reposition action with FLY.','An operative can only use this weapon during the Skytorch Assault action.')
body(23,'Skytorch Assault · 2AP','Выполните бесплатно «Перемещение» (Reposition). Во время него обязательно используйте Полёт (FLY) и увеличьте MOVE на 2 дюйма. Затем выполните бесплатно «Стрельбу» (Shoot), используя только профиль Небесного факела (Skytorch). Нельзя выполнять это действие с приказом «Скрытность» (Conceal) либо в дистанции контроля врага.','Perform a free Reposition action; you must use FLY and add 2" to Move for that action. Then perform a free Shoot action using only the skytorch profile. This operative cannot perform this action while it has a Conceal order or while within enemy control range.',append=True,hr='Атака небесным факелом · 2 AP (Skytorch Assault)')
edit(24,'Communion restrictions','2. Выполняя действие «Атака» (Charge), дружественный оперативник Веспидов-жалоносцев','2. Выполняя действие «Атака» (Charge), дружественный оперативник Веспидов-жалоносцев, кроме Дрона (DRONE),','2. Whenever a friendly VESPID STINGWING operative performs the Charge','2. Whenever a friendly VESPID STINGWING operative (excluding DRONE) performs the Charge')
b=old(25,'Living Metal');body(25,'Living Metal',b['russian'],b['english'].replace('after all other rules','before all other faction rules').replace('regains D3+1','regains up to D3+1'))
body(26,'Countertemporal Nanomine','1 AP. Разместите маркер Наномины противовременного поля (Countertemporal Nanomine) в пределах 8 дюймов от этого оперативника: маркер должен быть видим ему либо находиться на высоте (Vantage) видимого ему элемента террейна. Пока враг в пределах 4 дюймов от маркера, уменьшите его MOVE на 2 дюйма. Удалите маркер при начале следующей активации этого оперативника, его выведении из строя либо повторном выполнении действия дружественным оперативником, что наступит раньше. Нельзя выполнять в дистанции контроля врага.','1AP. Place the Countertemporal Nanomine marker visible to and within 8" of this operative, or within 8" of it and on Vantage terrain of a terrain feature visible to it. Enemy operatives within 4" of the marker have 2" subtracted from Move. Remove it at the start of this operative’s next activation, its incapacitation or this action being performed again by a friendly operative, whichever comes first. Cannot perform within enemy control range.')
body(27,'Timesplinter','1 AP. Выберите использованного (Expended) дружественного оперативника Круга Иеротек (HIEROTEK CIRCLE), видимого этому оперативнику и в пределах 5 дюймов от него. Уберите выбранного оперативника из зоны боя и выставьте заново в допустимом месте, видимом этому оперативнику и в пределах 5 дюймов от него по горизонтали. «Средство связи» (Comms Device) влияет только на первую дистанцию. Нельзя выполнять в дистанции контроля врага, в первом раунде либо если дружественный оперативник уже выполнял это действие в этом раунде.','1AP. Select one expended friendly HIEROTEK CIRCLE operative visible to and within 5" of this operative. Remove it and set it up in a legal location visible to and within 5" horizontally of this operative. Comms Device affects only the first distance. Cannot perform within enemy control range, during the first turning point or if a friendly operative has already performed this action during this turning point.')
u=edit(28,'Magnification Conduits','не находиться в дистанции контроля врагов','не находиться в дистанции контроля врагов','with an Engage order visible to that operative','with an Engage order, not within control range of enemy operatives and visible to that operative')
edit(29,'Chronometron','стреляет по выбранному бойцу, сражается с ним или отвечает на его удар','стреляет по выбранному бойцу','shoots, fights or retaliates against','shoots against')
for id in q[30]['localIds']:
 body(30,'Interstitial Command','1 AP, ПОДДЕРЖКА (SUPPORT). Выберите другого дружественного оперативника Круга Иеротек (HIEROTEK CIRCLE), кроме Подмастерья (APPRENTEK) и Криптека (CRYPTEK). Он должен быть видим этому оперативнику и в пределах 6 дюймов от него; либо видим дружественному Деспотеку (DESPOTEK) и в пределах 6 дюймов от него, при этом Деспотек видим этому оперативнику. Выбранный оперативник немедленно бесплатно выполняет действие стоимостью 1 AP, перемещаясь либо выставляясь заново не дальше чем на 2 дюйма. Нельзя выбрать действие, уже выполненное выбранным оперативником в этом раунде; он также не может повторить выбранное действие в этом раунде. Нельзя выполнять это действие в дистанции контроля врага либо во время контрдействия (Counteract).','1AP, SUPPORT. Select another friendly HIEROTEK CIRCLE operative excluding APPRENTEK and CRYPTEK visible to and within 6" of this operative, or visible to and within 6" of a friendly DESPOTEK that is visible to this operative. The selected operative can immediately perform a free 1AP action, but cannot move or be removed and set up more than 2", perform an action it has already performed during this turning point, or perform that action again during this turning point. This operative cannot perform this action within enemy control range or while counteracting.',id=id)
 if id=='93f9bd78cd76e0bc':
  u=out[-1]['blocks'][0];u['russian']=u['russian'].replace('действие стоимостью 1 AP,','действие стоимостью 1 AP, кроме «Ускорения» (Accelerate),');u['english']=u['english'].replace('a free 1AP action,','a free 1AP action (excluding Accelerate),')
for id in q[31]['localIds']:
 edit(31,'Scuttler','его нельзя выбрать допустимой целью;','его нельзя выбрать допустимой целью, кроме выбора цели в пределах 2 дюймов;','cannot be selected as a valid target,','cannot be selected as a valid target except being within 2",',id)
extra(32,'Reanimated Function','Для операции «Мученики» (Martyrs) из Approved Ops 2025 эта уловка не имеет эффекта.','For Martyrs (Approved Ops 2025), this ploy has no effect.')
edit(33,'Canoptek Repair','восстанавливает 2D3','восстанавливает до 2D3','regain 2D3','regain up to 2D3')
body(34,'Augment Weapon · 1AP · SUPPORT','Выберите дружественного оперативника Круга Иеротек (HIEROTEK CIRCLE), видимого этому оперативнику и в пределах 6 дюймов от него. Выберите одно оружие на карточке союзника и два правила для него: «Смертоносное 5+» (Lethal 5+), «Рассечение» (Rending), «Насыщение» (Saturate), «Сокрушительное» (Severe). Они действуют до начала следующей активации этого оперативника, его выведения из строя либо повторного выполнения действия дружественным оперативником, что наступит раньше. Для Посоха света (Staff of light) и Чародейского проводника (Arcane conduit) выберите только один профиль: стрелковый либо ближнего боя. Нельзя выполнять в дистанции контроля врага.','SUPPORT. Select one friendly HIEROTEK CIRCLE operative visible to and within 6" of this operative. Until the start of this operative’s next activation, its incapacitation or this action being performed again by a friendly operative (whichever comes first), select two rules from Lethal 5+, Rending, Saturate and Severe for one weapon from the selected operative’s datacard. For a staff of light or arcane conduit select either its ranged or melee profile only. Cannot perform within enemy control range.',id='fffb0948d21cd1a7',append=True,hr='Усилить оружие · 1 AP · ПОДДЕРЖКА (Augment Weapon)')
edit(35,'Blink Pack',' Нельзя совершать скачок в активацию, в которой выполняется рывок (Dash), и наоборот.','',' It cannot warp-jump in an activation in which it performs Dash, and vice versa.','')
u=edit(36,'Erudite Hunter','действие перемещения','действие, во время которого он перемещается','a move action','an action in which it moves');u['russian']+=' В тесном бою (Close Quarters) игнорируйте стены (Wall), сравнивая дистанцию до и после перемещения.';u['english']+=' In Close Quarters, ignore Wall terrain when determining whether it ends further away.'
body(37,'In Midnight Clad','Когда враг стреляет по дружественному оперативнику Когтя возмездия (NEMESIS CLAW), союзник считается заслонённым (Obscured), если выполнены оба условия:\n• Он дальше 8 дюймов от видимых ему врагов.\n• Он в пределах 1 дюйма от тяжёлого террейна (Heavy), расположенного не ниже него, либо часть его подставки находится под высотой (Vantage).','Whenever an enemy shoots a friendly NEMESIS CLAW operative, it is obscured if both apply: it is more than 8" from enemy operatives visible to it; it is within 1" of Heavy terrain that is not lower than it, or any part of its base is underneath Vantage terrain.')
edit(38,'Poison Objective','маркер оказывается в зоне контроля вражеского оперативника без вашего жетона','вражеский оперативник без вашего жетона оспаривает этот маркер','that marker is within control range of an enemy operative that does not have one of your Terrorchem tokens','an enemy operative that does not have one of your Terrorchem tokens contests that objective marker')
body(39,'Terrorchem*','На шаге разрешения кубиков атаки (Resolve Attack Dice), если критическими успехами нанесён урон, включая урон от «Опустошительного» (Devastating), цель оружия получает ваш жетон Террохимикатов (Terrorchem), если у неё его ещё нет. При каждой активации оперативника с вашим жетоном Террохимикатов нанесите ему D3 урона.','In the Resolve Attack Dice step, if critical successes inflict damage (including Devastating damage), the operative this weapon is used against gains one of your Terrorchem tokens if it does not already have one. Whenever an operative with one of your Terrorchem tokens is activated, inflict D3 damage on it.')
extra(40,'Prescience','В конце каждого раунда сбросьте все оставшиеся очки Предвидения (Prescience).','Discard all remaining Prescience points at the end of each turning point.')
extra(41,'Death to the False Emperor','Применяйте эту уловку после броска кубиков атаки дружественного оперативника.','Use this ploy after rolling the friendly operative’s attack dice.')
body(42,'Preysight','Когда дружественный оперативник Когтя возмездия (NEMESIS CLAW) выполняет «Стрельбу» (Shoot), можно применить это правило. До конца действия его стрелковое оружие получает «Дальность 6 дюймов» (Range 6") и «Обнаружение в лёгком укрытии» (Seek Light).','Whenever a friendly NEMESIS CLAW operative performs Shoot, you can use this rule. Until the end of the action its ranged weapons have Range 6" and Seek Light.')
extra(43,'Return to Darkness','За это действие нельзя переместиться дальше 4 дюймов. В тесном бою (Close Quarters) игнорируйте стены (Wall), сравнивая дистанции до врагов.','It cannot move more than 4" during that action. In Close Quarters, ignore Wall terrain when comparing distances to enemy operatives.')
body(44,'Vox Scream','Примените, когда противник собирается активировать врага, видимого дружественному оперативнику Когтя возмездия (NEMESIS CLAW). Бросьте D6: если результат выше APL врага, противник не может активировать его в эту активацию. Если результат равен APL или ниже, уловка не применяется: верните потраченные CP; нельзя снова применять её в этом раунде. Если нет других врагов, которых можно активировать, уловка не имеет эффекта.','Use when your opponent would activate an enemy visible to a friendly NEMESIS CLAW operative. Roll D6: if higher than the enemy’s APL it cannot activate during this activation. If equal or lower, do not use the ploy, refund the CP and do not use it again during this turning point. If no other enemy operative is eligible, the ploy has no effect.')
extra(45,'Chain Snare','Если выпал хотя бы один результат 4+, в этом раунде больше нельзя применять это правило.','If any result is 4+, you cannot use this rule again during this turning point.')
edit(46,'Aerial Guidance (1AP)','видимый ему и находящийся в пределах 6 дюймов от него','находящийся в пределах 6 дюймов от него','visible to and within 6 inches of this operative','within 6 inches of this operative')
edit(47,'Neutron Fragment','На шаге подготовки (Ready) каждой стратегической фазы отдельно нанесите D3 урона каждому оперативнику за каждый такой жетон у него.','При активации оперативника нанесите ему D3 урона за каждый такой жетон у него.','In the Ready step of each Strategy phase, separately inflict D3 damage on each operative for each Neutron Fragment token it has.','Whenever an operative with your Neutron Fragment tokens is activated, inflict D3 damage on it for each token it has.')
u=edit(48,'Rule','перебросьте любое количество защитных кубиков','выберите одно значение результата и перебросьте все свои кубики защиты с этим результатом','you can re-roll any of your defence dice','select one result face and re-roll your defence dice showing that result');u['russian']=u['russian'].replace('перебросьте один защитный кубик','можно перебросить один защитный кубик')
edit(49,'Rule','В зоне Killzone: Gallowdark расстояние можно измерять сквозь террейн «Стена» (Wall).','В тесном бою (Close Quarters) туннель (TUNNEL) и дистанции между его маркерами можно измерять сквозь стены (Wall).','(in Killzone: Gallowdark, this distance can be measured through Wall terrain)','(in Close Quarters, your TUNNEL and distances between its markers can be measured through Wall terrain)')
extra(50,'Burrow (1AP)','Нельзя выполнять действие, если оперативник не находится под землёй либо на вашем туннеле (TUNNEL).','Cannot perform this action unless this operative is underground or on your TUNNEL.')
u=edit(51,'Subterranean Ambush','Раз за раунд после','Раз за раунд в фазе перестрелки (Firefight) после','Once per turning point, after','Once per turning point during the Firefight phase, after');u['russian']=u['russian'].replace('прервать активацию или контратаку врага','прервать ход игры').replace('врага, если это возможно','врага, если это возможно и уместно');u['english']=u['english'].replace('interrupt that enemy operative’s activation/counteraction','interrupt').replace('if possible.','if possible and relevant.')
edit(52,'Distend Dorsal Sac (1AP)','или не выполнит действие «Зарыться» (Burrow) (что наступит раньше)','либо не выполнит действие «Зарыться» (Burrow) либо не выполнит это действие повторно (что наступит раньше)','or until it performs the Burrow action (whichever comes first)','or until it performs the Burrow action or until it performs this action again (whichever comes first)')
edit(53,'Rule','Выберите дружественного равенера.','Выберите дружественного равенера (RAVENER), находящегося в зоне боя.','Select one friendly RAVENER operative.','Select one friendly RAVENER operative in the killzone.')
u=edit(54,'Toxic Lunge (1AP)','Выберите вражеского оперативника в пределах 2 дюймов','Выберите видимого вражеского оперативника в пределах 2 дюймов','Select one enemy operative within 2″','Select one enemy operative visible to and within 2″');u['russian']=u['russian'].replace('Если он находится под землёй','Если этот оперативник находится под землёй');u['russian']+=' Если враг находится в дистанции контроля этого оперативника, нельзя выбрать врага вне этой дистанции.';u['english']+=' If an enemy is within this operative’s control range, you cannot select one outside it.'
b=old(55,'Synaptic Link (Strategic Gambit)');body(55,'Synaptic Link (Strategic Gambit)',b['russian'],b['english'].replace('higher, gain 1CP; equal, nothing happens; lower, inflict damage on this operative equal to the result.','at least twice as high, gain 1CP; less than the turning point number, inflict damage equal to the result; any other result has no effect.'))
for p in out:
 for u in p.get('blocks',[]):u['russian']=re.sub(r'\bОД\b','AP',u['russian'])
(R/'ru-current-updates-d.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf8');print(json.dumps({'patches':len(out),'deferred':['D2 effective body']}))
