"""Root full-body corrections for Sanctifiers, Death Korps, Exaction and Pathfinders."""
import json,re
from pathlib import Path
ROOT=Path(__file__).parent
def read(n):return json.loads((ROOT/n).read_text(encoding='utf8'))
a=read('inventory/current-team-audit-c-stable.json');q=a['queue'];c=read('inventory/current-rule-base-cards.json');out=[]
def old(n,heading,id=None):return next(b for b in c[id or q[n]['localIds'][0]].get('blocks',[]) if b.get('headingEnglish')==heading)
def text(n,heading,ru,en,append=False,ruHeading=None,id=None):
 x=q[n];id=id or x['localIds'][0];s=a['sources']['teams'][x['team']]
 u={'heading':heading,'russian':ru,'english':en,'proseTitles':[heading.split(' ·')[0].split(' (')[0].split(':')[0]]}
 if append:u.update(append=True,headingRussian=ruHeading)
 p={'id':id,'expectedTitle':c[id]['titleEnglish'],'team':x['team'],'source':{'officialPdf':s['officialPdf'],'date':s['officialCatalogLastUpdated'],'wahapedia':s['wahapedia'],'checkedOn':'2026-10-05',**x['source']},'blocks':[u]};out.append(p);return u
def replace(n,heading,ro,rn,eo,en,id=None):
 b=old(n,heading,id);assert ro in b['russian'],(n,ro);assert eo in b['english'],(n,eo)
 return text(n,heading,b['russian'].replace(ro,rn),b['english'].replace(eo,en),id=id)
def extend(n,heading,ru,en):
 b=old(n,heading);return text(n,heading,b['russian']+'\n'+ru,b['english']+' '+en)
replace(0,'Weapon rule','Если вы сохранили хотя бы один критический успех','Если вы нанесли урон хотя бы одним критическим успехом','If you retain any critical successes','If you inflict damage with any critical successes')
replace(1,'Sermon effect','урон со значением 3 или выше','урон со значением 4 или выше','Dmg of 3 or more','Dmg of 4 or more')
replace(2,'Rule','ближе к дружественному оперативнику ORATOR.','ближе к дружественному Проповеднику (ORATOR), при этом хотя бы один из них должен видеть другого.','closer to a friendly ORATOR operative.','closer to a friendly ORATOR operative and visible to it (or vice versa).')
replace(3,'Rule','бросьте 2D6','бросьте 3D6','roll 2D6','roll 3D6')
replace(4,'Twin Torrent','Выберите до двух допустимых целей.','Выберите до двух разных допустимых целей вне дистанции контроля дружественных оперативников.','Select up to two valid targets.','Select up to two different valid targets that aren’t within control range of friendly operatives.')
b=old(5,'Null Skull');text(5,'Null Skull',b['russian'].replace('6 дюймов','4 дюймов').replace('ОД','AP'),b['english'].replace('6"','4"'))
replace(6,'Defend the Faith','оспаривает маркер цели','контролирует маркер цели','contests an objective marker','controls an objective marker')
text(7,'Lead the Procession','В каждом раунде после первого, когда этот оперативник является Проповедником (ORATOR) и выполняет «Атаку» (Charge), «Отступление» (Fall Back) или «Перемещение» (Reposition) в свою активацию, можно применить это правило до его перемещения. Определите остальных дружественных Освятителей (SANCTIFIER), получающих эффект Проповеди (SERMON), если хотя бы один из них и этого оперативника видит другого.\nПосле окончания действия этого оперативника каждый из выбранных союзников может немедленно бесплатно выполнить Charge, Fall Back или Reposition. Выбирайте действие отдельно для каждого и порядок их действий. Каждый из них может переместиться либо быть убран и заново выставлен не дальше чем на 3 дюйма и должен закончить перемещение там, где по-прежнему получает Проповедь. Если этот оперативник выведен из строя до полного разрешения правила, например прерыванием по правилу «Дозор» (Guard), не убирайте его из зоны боя до полного разрешения правила.',en='In each turning point after the first, whenever this operative is an ORATOR and performs Charge, Fall Back or Reposition during its activation, you can use this rule before it moves. Determine each other friendly SANCTIFIER benefitting from the SERMON and visible to this operative (or vice versa). After this operative ends that action, each selected friendly can immediately perform a free Charge, Fall Back or Reposition in your chosen order (choose separately for each), but cannot move more than or be removed and set up more than 3" and must end still benefitting from the SERMON. If this operative is incapacitated before full resolution, e.g. Guard interruption, do not remove it until this rule is resolved.')
replace(8,'Cherub','например, над террейном с высотной позицией (Vantage terrain)).','например, над «Обнаружением» (Seek) и высотой (Vantage)), кроме выбора цели в пределах 2 дюймов.','(e.g. Vantage terrain).','(e.g. Seek, Vantage terrain) except being within 2".')
replace(9,'Imperial Cult Devotion','выведен из строя в пределах 6 дюймов','выведен из строя, будучи видимым этому оперативнику и в пределах 6 дюймов','is incapacitated within 6"','is incapacitated while visible to and within 6"')
replace(10,'Cult Icon','в пределах 6 дюймов','в пределах 4 дюймов','within 6"','within 4"')
text(11,'Conversion Field','Когда оперативник дальше 6 дюймов от этого оперативника стреляет по дружественному Освятителю (SANCTIFIER) в пределах 6 дюймов от этого оперативника, улучшите SAVE дружественного Освятителя на 1.',en='Whenever an operative more than 6" from this operative is shooting a friendly SANCTIFIER operative within 6" of this operative, improve that friendly operative’s Save stat by 1.')
extend(13,'Bruiser','Если этот оперативник выведен из строя во время действия «Сражаться» (Fight), до его удаления из зоны боя можно нанести врагу в этой последовательности удар одним из ваших неразыгранных успехов.','If this operative is incapacitated during the Fight action, you can strike the enemy operative in that sequence with one of your unresolved successes before it is removed from the killzone.')
replace(14,'Spot · 1AP · SUPPORT','Один раз за раунд, когда','До конца раунда каждый раз, когда','Once during this turning point, when','Until the end of the turning point, whenever')
extend(15,'Detonate','В зонах боя с правилами тесного боя (Close Quarters) дистанционный детонатор (Remote Detonator) получает правило «Смертоносное 5+» (Lethal 5+).','In close quarters killzones, the Remote Detonator has Lethal 5+.')
text(16,'Bring it Down!','Стратегический гамбит (STRATEGIC GAMBIT), если этот оперативник находится в зоне боя. Выберите одного врага: до шага готовности (Ready) следующей фазы стратегии он получает ваш жетон «Уничтожить цель!» (Bring it Down!). Когда дружественный оперативник Корпуса Смерти (DEATH KORPS) стреляет по этому врагу, сражается с ним или отвечает ему в ближнем бою, оружие союзника получает правило «Карающее» (Punishing).',en='STRATEGIC GAMBIT if this operative is in the killzone. Select one enemy operative. Until the Ready step of the next Strategy phase it gains your Bring it Down! token. Whenever a friendly DEATH KORPS operative is shooting against, fighting against or retaliating against that enemy operative, its weapons have Punishing.',append=True,ruHeading='Уничтожить цель!')
replace(17,'Rule','бесплатно выполнить одно действие.','бесплатно выполнить одно действие; для этого можно изменить его приказ.','perform one free action.','perform one free action (you can change its order to do so).')
medic=c['7b57d5bb83d8aba7']['blocks'][0]
for n,faction,ruFaction in [(18,'DEATH KORPS','Корпуса Смерти (DEATH KORPS)'),(24,'EXACTION SQUAD','Карательного отряда (EXACTION SQUAD)'),(36,'PATHFINDER','Следопытов (PATHFINDER)')]:
 en=medic['english'].replace('DEATH KORPS',faction);ru=medic['russian'].replace('DEATH KORPS',ruFaction)
 if n==36:en=en.replace('another friendly PATHFINDER operative','another friendly PATHFINDER operative (excluding DRONE)');ru=ru.replace('другой дружественный оперативник Следопытов (PATHFINDER)','другой дружественный оперативник Следопытов (PATHFINDER), кроме Дрона (DRONE),')
 text(n,'Medic!',ru,en)
replace(19,'Medikit · 1AP','восстанавливает 2D3 потерянных ран','восстанавливает до 2D3 потерянных ран','regain 2D3 lost wounds','regain up to 2D3 lost wounds')
replace(20,'Attack Pattern: Strategic Gambit','один боевой режим','два разных боевых режима','select one of the following attack patterns','select two of the following attack patterns')
replace(22,'R-VR Command (0AP)','измените его боевой режим','измените один из его боевых режимов','change its attack pattern','change one of its attack patterns')
for id,heading in [('d8adfd099d9ce7c9','Spot (1AP)'),('49d94710ae79ea39','Spot · 1 AP')]:
 replace(23,heading,'видимого этому оперативнику.','видимого этому оперативнику и в пределах 8 дюймов от него.','visible to this operative.','visible to and within 8" of this operative.',id=id)
replace(25,'Special-Issue Shells','Один раз за раунд','До двух раз за раунд','Once per turning point','Up to twice per turning point')
extend(26,'Manacles','Если выпал хотя бы один результат 4+, в этом раунде «Наручники» (Manacles) больше применять нельзя.','If any result is a 4+, you cannot use this rule again during this turning point.')
replace(28,'Additional rules','1 жетон: «Насыщение огнём» (Saturate). 2 жетона: «Сбалансированное» (Balanced).','1 жетон: «Насыщение» (Saturate) и «Сбалансированное» (Balanced). 2 жетона: улучшите HIT стрелкового оружия на 1, максимум до 3+.','1 token: Saturate. 2 tokens: Balanced.','1 token: Saturate and Balanced. 2 tokens: Improve ranged Hit by 1, to a maximum of 3+.')
u=out[-1]['blocks'][0];u['russian']+=' 5 жетонов: «Обнаружение» (Seek).';u['english']+=' 5 tokens: Seek.'
extend(29,'Saviour Protocols','Заменяющий дрон получает укрытие (Cover) или заслонение (Obscured) только если их имела исходная цель.','That other operative is only in cover or obscured if the original target was.')
extend(30,'Point-Blank Fusillade','Если дружественный оперативник готов (Ready), имеет приказ «Бой» (Engage) и отвечает в ближнем бою импульсным оружием (Pulse weapon), вы разыгрываете первый кубик атаки: защитник действует раньше атакующего.','If that friendly operative is ready, has an Engage order and is retaliating with a pulse weapon, you resolve the first attack dice (i.e. defender instead of attacker).')
extend(31,'Recon Sweep','Эту уловку нельзя использовать в первом раунде.','You cannot use this ploy during the first turning point.')
u=replace(32,'Photon Grenade','Выберите допустимую для него цель','Выберите одного видимого этому оперативнику врага','Select a valid target for this operative','Select one enemy operative visible to this operative')
u['russian']=u['russian'].replace('; цель также не может выполнять действие «Рывок» (Dash).','.')
u['english']=u['english'].replace(' and it cannot perform the Dash action','')
replace(33,'High-Intensity Markerlight','Один раз за раунд','До двух раз за раунд','Once per turning point','Up to twice per turning point')
u=text(34,'Art of War · Once per battle Strategic Gambit','Стратегический гамбит (STRATEGIC GAMBIT), если этот оперативник находится в зоне боя. Выберите один эффект до конца раунда. Каждый вариант можно выбирать не больше одного раза за бой:\n• Мон’ка (Mont’ka): увеличьте MOVE дружественных Следопытов (PATHFINDER) на 1 дюйм.\n• Кауйон (Kauyon): дружественные Следопыты с приказом «Скрытность» (Conceal) могут бесплатно выполнять «Маркерный луч» (Markerlight) в свою активацию.',en='STRATEGIC GAMBIT if this operative is in the killzone. Select one option and apply its rules until the end of the turning point. You cannot select each option more than once per battle. Mont’ka: Add 1" to friendly PATHFINDER Move. Kauyon: Friendly PATHFINDER operatives can perform a free Markerlight during their activation if they have Conceal.');u.update(newHeadingEnglish='Art of War · Strategic Gambit',headingRussian='Военное искусство · стратегический гамбит')
u=text(35,'Multi-Dimensional Vision · 1 AP','Когда этот оперативник стреляет, вражеские оперативники не могут считаться заслонёнными (Obscured).',en='Whenever this operative is shooting, enemy operatives cannot be obscured.');u.update(newHeadingEnglish='Multi-Dimensional Vision',headingRussian='Многомерное зрение',moveCategory='abilities')
text(37,'Grav-Inhibitor','Когда враг выполняет действие с перемещением, кроме «Рывка» (Dash), если он перемещается в место, видимое этому оперативнику и в пределах 6 дюймов от него, считайте пройденную дистанцию на 2 дюйма больше. Игнорируйте дополнительную дистанцию по особенностям террейна «Заграждающий» (Obstructing) и «Доступный» (Accessible).\nКогда враг сражается или отвечает в ближнем бою, будучи видимым этому оперативнику и в пределах 6 дюймов от него, ухудшите HIT оружия ближнего боя врага на 1. Это суммируется с ранением (Injured).',en='Whenever an enemy operative performs an action in which it moves (excluding Dash), if it would move visible to and within 6" of this operative, treat the distance as an additional 2" and ignore additional distances from Obstructing and Accessible terrain. Whenever an enemy is fighting or retaliating while visible to and within 6" of this operative, worsen its melee Hit by 1. This is cumulative with being injured.')
for p in out:
 for u in p['blocks']:
  u['russian']=re.sub(r'\bОД\b','AP',u['russian'])
  if p['id'] in ['4c321c989cc406b3','cf28c3ad159b7f6b','d8adfd099d9ce7c9']:u['russian']=u['russian'].replace('скрытым от обзора','заслонённым (Obscured)').replace('скрытым','заслонённым')
(ROOT/'ru-current-updates-c-text.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
print(json.dumps({'fullBodyPatches':len(out),'additionalCoverage':['create-current-c-rest-updates.py','create-missing-cards.py']}))
