"""New Russian cards for the source pack's missing Battleclade rules."""
import json,hashlib,re
from pathlib import Path
from reportlab.pdfgen import canvas
import pypdfium2
R=Path(__file__).parent
def read(n):return json.loads((R/n).read_text(encoding='utf8'))
s=read('inventory/critic-battleclade-effective-source.json');cards={};sources=read('inventory/image-sources.json');assets=read('inventory/card-assets.json');manifest=[];activeTeam='Battleclade';activeRussian='БОЕВАЯ КЛАДА'
# Resolve the authoritative URL from the current audit instead of inventing one.
sourceUrl=read('inventory/critic-full-team-audit-c.json')['sources']['teams']['Battleclade']['officialPdf']
provenance={'officialPdf':sourceUrl,'date':'2026-08-26','wahapedia':'https://wahapedia.ru/kill-team3/kill-teams/battleclade/','checkedOn':'2026-10-05'}
names={
'Battleclade Technoarcheologist':'Техноархеолог','Battleclade Auto-Proxy Servitor':'Автопрокси-сервитор','Battleclade Breacher Servitor':'Сервитор-проломщик','Battleclade Combat Servitor':'Боевой сервитор','Battleclade Gun Servitor':'Стрелковый сервитор','Battleclade Servitor Underseer':'Сервитор-поднадзиратель','Battleclade Technomedic Servitor':'Сервитор-техномедик',
'Noospheric Possession':'Ноосферическая одержимость','Duty of Reclamation':'Долг возвращения','Incantation of the Iron Soul':'Заклинание железной души','Prioritised Acquisition':'Приоритетное приобретение','System Exorcism':'Изгнание из системы','Remote Access':'Удалённый доступ','Auto-Ferric Supplication':'Автоферрическая молитва','Servile Surrogacy':'Сервильное замещение','Covert Guises':'Скрытые обличья','Electromantic Capacitors':'Электромантические конденсаторы','Concealed Apparatus':'Скрытое вооружение','Neurocyclic Reserve Cells':'Нейроциклические резервные элементы',
'Seeker of Divine Arcana':'Искатель священных тайн','Omniscanner':'Омнисканер','Achillan Eye':'Ахилланское око','Gaze of the Omnissiah':'Взор Омниссии','Breach':'Пролом','Datacoronal Accumulator':'Датакорональный накопитель','Network Override':'Переопределение сети','Mechanosuture Array':'Механошовная система','Expedient Repair':'Срочный ремонт'}
names.update({'Archetypes':'Архетипы','Operatives':'Оперативники','Selection restrictions':'Ограничения состава','Transfer Power':'Передача энергии','Network Counteract':'Сетевое контрдействие','System Exorcism: interruption':'Изгнание из системы: прерывания','Remote Access: placing markers':'Удалённый доступ: размещение маркеров','Network Counteract: no ready enemies':'Сетевое контрдействие: нет готовых врагов','Network Counteract and Guard':'Сетевое контрдействие и дозор','System Exorcism: area effects':'Изгнание из системы: области','System Exorcism: repeated tokens':'Изгнание из системы: повторные жетоны','Markers and tokens':'Маркеры и жетоны'})
texts={
'Noospheric Possession':'ПОДДЕРЖКА (SUPPORT). Пока дружественный Сервитор Боевой клады (BATTLECLADE SERVITOR) находится в пределах 6 дюймов от дружественного Автопрокси (AUTO-PROXY) или Сервитора-поднадзирателя (SERVITOR UNDERSEER), его оружие получает «Точное 1» (Accurate 1). Чтобы «Средство связи» (Comms Device) добавило 3 дюйма к этой дистанции, оперативник, от которого она измеряется, должен контролировать ваш маркер средства связи.',
'Duty of Reclamation':'Один раз за действие можно применить «Командный переброс» (Command Re-roll) за 0 CP, если кубик атаки или защиты был брошен за дружественного оперативника Боевой клады (BATTLECLADE), оспаривающего маркер цели либо один из ваших маркеров миссии.',
'Incantation of the Iron Soul':'Каждый раз, когда кубик атаки наносит дружественному оперативнику Боевой клады (BATTLECLADE) 3 или больше урона, бросьте D6. На 4+ уменьшите нанесённый этим кубиком урон на 1.',
'Prioritised Acquisition':'Выберите маркер цели либо один из ваших маркеров миссии. При определении контроля над ним считайте суммарный APL оспаривающих его дружественных оперативников Боевой клады (BATTLECLADE) на 1 выше, если хотя бы один такой оперативник оспаривает маркер. Это не изменение характеристики APL: другие изменения складываются с ним. Пока дружественный оперативник Боевой клады в пределах 3 дюймов от маркера, увеличьте ATK его оружия ближнего боя на 1, максимум до 4.',
'System Exorcism':'Примените эту уловку, когда собираетесь активировать дружественного оперативника Боевой клады (BATTLECLADE). Уберите один эффект правил либо изменение характеристики, которое противник применил к нему: например жетон яда (Poison), −1 APL или запрет активации либо действий. Затем активируйте оперативника. Уловка не позволяет восстанавливать потерянные раны, игнорировать ранение (Injured) или убирать правила набора миссий.',
'Remote Access':'Примените эту уловку в активацию дружественного Техножреца Боевой клады (BATTLECLADE TECH-PRIEST). Один раз в ту активацию используйте один вариант:\n• Для миссионного действия, обычно требующего маркера в дистанции контроля оперативника, вместо этого достаточно маркера в пределах 4 дюймов от него. Маркер не должен оспариваться врагами; при проверке игнорируйте врагов в дистанции контроля других дружественных оперативников Боевой клады. Это правило имеет приоритет над условиями действия.\n• Для «Управлять люком» (Operate Hatch) точка доступа может находиться в пределах 4 дюймов от оперативника вместо его дистанции контроля.',
'Auto-Ferric Supplication':'Примените эту уловку, когда оперативник стреляет по дружественному Техножрецу Боевой клады (BATTLECLADE TECH-PRIEST), в начале шага броска кубиков атаки (Roll Attack Dice). До конца последовательности игнорируйте правило «Бронебойное» (Piercing).',
'Servile Surrogacy':'Примените эту уловку, когда дружественный Техножрец Боевой клады (BATTLECLADE TECH-PRIEST) выбран допустимой целью «Стрельбы» (Shoot) либо противником для «Ближнего боя» (Fight). Выберите дружественного Сервитора Боевой клады (BATTLECLADE SERVITOR), видимого техножрецу и в пределах 3 дюймов от него. Сервитор становится целью либо противником для боя вместо техножреца, даже если обычно такой выбор недопустим. При Fight считайте сервитора находящимся в дистанции контроля сражающегося оперативника до конца действия. При Shoot сервитор получает укрытие (Cover) и заслонение (Obscured), только если их имела исходная цель. Уловка не действует при Shoot оружием с «Взрывом» (Blast) или «Потоком» (Torrent).',
'Covert Guises':'После раскрытия этого варианта снаряжения бросьте D3. В качестве стратегического гамбита (STRATEGIC GAMBIT) в первом раунде число дружественных оперативников Боевой клады (BATTLECLADE), равное результату броска, может немедленно бесплатно выполнить «Перемещение» (Reposition), если они целиком в вашей зоне высадки. Каждый должен закончить перемещение целиком в пределах 3 дюймов от зоны высадки. Ваш Техноархеолог (TECHNOARCHEOLOGIST) не может выполнить больше одного Reposition в фазе стратегии первого раунда, включая «Искателя священных тайн» (Seeker of Divine Arcana).',
'Electromantic Capacitors':'Оружие ближнего боя дружественных оперативников Боевой клады (BATTLECLADE) получает «Потрясение» (Shock). Когда дружественный оперативник Боевой клады отвечает в ближнем бою, его оружие ближнего боя также получает «Сокрушительное» (Severe).',
'Concealed Apparatus':'Один раз за бой один Боевой сервитор (COMBAT SERVITOR) либо Стрелковый сервитор (GUN SERVITOR) может использовать другой вариант оружия на своей карточке, который он не выбрал для боя.',
'Neurocyclic Reserve Cells':'Один раз за раунд при передаче энергии (TRANSFER POWER) можно применить это правило, чтобы передать энергию за 0 AP. Это имеет приоритет над обычными правилами Ноосферической сети (Noospheric Network).',
'Seeker of Divine Arcana':'СТРАТЕГИЧЕСКИЙ ГАМБИТ (STRATEGIC GAMBIT). Немедленно измените приказ этого оперативника и/или бесплатно выполните им «Омнисканер» (Omniscanner), «Отступление» (Fall Back), «Положить маркер» (Place Marker), «Поднять маркер» (Pick Up Marker), «Перемещение» (Reposition) либо миссионное действие. При Fall Back или Reposition, если он не несёт маркер, он должен закончить перемещение в вашей зоне высадки — если невозможно, как можно ближе к ней — либо с маркером цели или одним вашим маркером миссии в своей дистанции контроля.',
'Omniscanner':'Выберите врага, видимого этому оперативнику либо находящегося в пределах 8 дюймов от него: враг получает ваш жетон Омнисканера (Omniscanner). Когда дружественный оперативник Боевой клады (BATTLECLADE) стреляет по врагу с вашим жетоном Омнисканера, сражается с ним либо отвечает ему в ближнем бою, его оружие получает «Непрерывное» (Ceaseless). Нельзя выполнять это действие в дистанции контроля врага.',
'Achillan Eye':'Когда дружественный оперативник Боевой клады (BATTLECLADE) стреляет по врагу, видимому этому оперативнику, стрелковое оружие союзника получает «Насыщение» (Saturate). Это правило не действует, пока этот оперативник находится в дистанции контроля врага.',
'Gaze of the Omnissiah':'Выберите врага, видимого этому оперативнику. До конца раунда каждый раз, когда дружественный оперативник Боевой клады (BATTLECLADE) стреляет по выбранному врагу, можно применить этот эффект: стрелковое оружие союзника получает «Обнаружение в лёгком укрытии» (Seek Light), а враг не может считаться заслонённым (Obscured). Нельзя выполнять это действие в дистанции контроля врага.',
'Breach':'Разместите один из своих маркеров Пролома (Breach) в дистанции контроля этого оперативника как можно ближе к элементу террейна в его дистанции контроля. Пока любой оперативник в пределах 1 дюйма от маркера, он считает части этого элемента террейна толщиной не больше 1 дюйма доступными (Accessible). Нельзя выполнять действие в дистанции контроля врага либо если в дистанции контроля этого оперативника нет террейна.',
'Datacoronal Accumulator':'ПОДДЕРЖКА (SUPPORT). Определите дружественных оперативников Боевой клады (BATTLECLADE) в пределах 6 дюймов от этого оперативника и/или дружественного Автопрокси (AUTO-PROXY), затем бросьте D3. Если результат не превышает число маркеров целей, которые оспаривают эти союзники, получите 1 CP. Чтобы «Средство связи» (Comms Device) добавило 3 дюйма к требуемой дистанции, оперативник, от которого она измеряется, должен контролировать ваш маркер средства связи. Нельзя выполнять действие в дистанции контроля врага.',
'Network Override':'ПОДДЕРЖКА (SUPPORT). Выберите дружественного Сервитора Боевой клады (BATTLECLADE SERVITOR) в пределах 6 дюймов от этого оперативника либо дружественного Автопрокси (AUTO-PROXY). Он немедленно выполняет Сетевое контрдействие (NETWORK COUNTERACT) без передачи энергии (TRANSFER POWER) либо бесплатно выполняет «Рывок» (Dash). Затем продолжите активацию этого оперативника. Чтобы «Средство связи» (Comms Device) увеличивало дистанцию, оперативник, от которого она измеряется, должен контролировать его маркер. Это действие можно выполнить дважды за активацию, выбирая каждый раз другого союзника. Нельзя выполнять его в дистанции контроля врага.',
'Mechanosuture Array':'Один раз за раунд, когда другой дружественный оперативник Боевой клады (BATTLECLADE), видимый этому оперативнику и в пределах 3 дюймов от него, должен быть выведен из строя, можно применить это правило, если ни один из них не находится в дистанции контроля врага. Союзник не выводится из строя: у него остаётся 1 рана и его нельзя вывести из строя до конца текущего действия. После действия он может немедленно бесплатно выполнить «Рывок» (Dash), закончив его в дистанции контроля этого оперативника. Если правило применено в активацию спасённого союзника, она заканчивается. Нельзя применять правило, если этот оперативник выведен из строя либо если это «Стрельба» (Shoot), при которой он станет основной или вторичной целью.',
'Expedient Repair':'Выберите дружественного оперативника Боевой клады (BATTLECLADE) в дистанции контроля этого оперативника: он восстанавливает до D3+3 потерянных ран. Нельзя выбрать оперативника, к которому в этом раунде применялась «Механошовная система» (Mechanosuture Array). Нельзя выполнять это действие в дистанции контроля врага.'}
weaponNames={'Eradication pistol':'Пистолет искоренения','Servo-arc claw':'Серводужная клешня','Taser goad':'Тазерное стрекало','Lascutter (close range)':'Лазрезак — в упор','Lascutter (short range)':'Лазрезак — короткая дистанция','Hydraulic pincer & lascutter':'Гидравлические клещи и лазрезак','Incendine igniter':'Инцендиновый воспламенитель','Meltagun':'Мелтаган','Phosphor blaster':'Фосфорный бластер','Servo-claw':'Сервоклешня','Heavy arc rifle':'Тяжёлая дуговая винтовка','Heavy bolter (focused)':'Тяжёлый болтер — прицельный огонь','Heavy bolter (sweeping)':'Тяжёлый болтер — веерный огонь','Augmetic claw':'Аугметическая клешня','Master-crafted radium pistol':'Мастерский радиевый пистолет','Dataspikes':'Датаиглы','Servo-chirurgic claw':'Сервохирургическая клешня'}
wrNames={'Range':'Дальность','Devastating':'Опустошительное','Lethal':'Смертоносное','Severe':'Сокрушительное','Shock':'Потрясение','Piercing Crits':'Бронебойное при критических успехах','Piercing':'Бронебойное','Saturate':'Насыщение','Torrent':'Поток','Blast':'Взрыв','Heavy (Dash only)':'Тяжёлое (только Dash)','Stun':'Оглушение','Brutal':'Жестокое','Balanced':'Сбалансированное','Rending':'Рассечение'}
def wr(s):
 if s=='-':return '—'
 return ', '.join(re.sub('|'.join(re.escape(k)for k in sorted(wrNames,key=len,reverse=True)),lambda m:wrNames[m[0]],x)+' ('+x+')'for x in s.split(', '))
def block(name,ru,en,ap=None):
 suffix=' · '+str(ap)+' AP' if ap is not None else ''
 return {'type':'paragraph','headingEnglish':name+suffix,'headingRussian':names.get(name,name)+suffix+' ('+name+')','english':en,'russian':ru,'currentRuleSource':provenance}
def add(name,ru,category,blocks,stats=None,weapons=None,footer=None):
 id=hashlib.sha256(('KT-RU-new-2026/'+name).encode()).hexdigest()[:16]
 d={'kind':'card','titleEnglish':name,'titleRussian':ru+' ('+name+')','categoryEnglish':activeTeam.upper()+' · '+category,'categoryRussian':activeRussian+' ('+activeTeam.upper()+') · '+{'OPERATIVE':'ОПЕРАТИВНИК','KILL TEAM':'ОТРЯД','FACTION RULE':'ПРАВИЛО ФРАКЦИИ','STRATEGY PLOY':'СТРАТЕГИЧЕСКАЯ УЛОВКА','FIREFIGHT PLOY':'УЛОВКА ПЕРЕСТРЕЛКИ','FACTION EQUIPMENT':'СНАРЯЖЕНИЕ ФРАКЦИИ','RULES COMMENTARY':'РАЗЪЯСНЕНИЯ ПРАВИЛ','TOKEN GUIDE':'ЖЕТОНЫ И МАРКЕРЫ'}[category],'blocks':blocks,'verifiedAgainstPixels':True,'generatedSupplement':True,'layoutRevision':1,'currentRuleSources':[provenance]}
 if stats:d['stats']={k:stats[x]for k,x in [('APL','APL'),('Move','MOVE'),('Save','SAVE'),('Wounds','WOUNDS')]}
 if weapons:d['weapons']=weapons
 if footer:
  terms={'BATTLECLADE':'Боевая клада','IMPERIUM':'Империум','ADEPTUS MECHANICUS':'Адептус Механикус','TECH-PRIEST':'Техножрец','LEADER':'Лидер','TECHNOARCHEOLOGIST':'Техноархеолог','AUTO-PROXY':'Автопрокси','SERVITOR':'Сервитор','BREACHER':'Проломщик','COMBAT':'Боевой','GUN':'Стрелковый','SERVITOR UNDERSEER':'Поднадзиратель сервиторов','MEDIC':'Медик','TECHNOMEDIC':'Техномедик'}
  tokens,base=footer.split('; ');d.update(footerEnglish=footer,footerRussian=', '.join(terms[k]+' ('+k+')'for k in tokens.split(', '))+' · '+base.replace('mm',' мм'))
 cards[id]=d;manifest.append({'id':id,'team':activeTeam,'name':name,'generatedSupplement':True})
 # Code-native source placeholder gives the renderer portrait geometry; it is never an original game asset.
 directory=R/'inventory/generated-card-sources';directory.mkdir(exist_ok=True)
 page=(950,550) if stats else (550,800)
 pdf=directory/(id+'.pdf');cv=canvas.Canvas(str(pdf),pagesize=page);cv.setTitle(name);cv.setFont('Helvetica',12);cv.drawString(15,page[1]-20,name);cv.showPage();cv.save()
 doc=pypdfium2.PdfDocument(str(pdf));img=doc[0].render(scale=2).to_pil();png=directory/(id+'.png');img.save(png);doc.close()
 digest=hashlib.sha256(png.read_bytes()).hexdigest();source={'id':id,'path':str(png),'url':str(png).replace('\\','/'),'sha256':digest,'width':page[0]*2,'height':page[1]*2,'sourceKind':'generated-vector-template','sourceDocument':sourceUrl}
 sources[:]=[x for x in sources if x['id']!=id];sources.append(source)
 if stats:
  assets[:]=[x for x in assets if x.get('generatedSupplementId')!=id];assets.append({'source':'teams','team':'Battleclade','path':'/generated-supplement/'+id,'generatedSupplementId':id,'face':{'id':id,'columns':1,'rows':1,'tile':0},'back':{}})
 return id
add('Battleclade Kill Team','Отряд Боевой клады','KILL TEAM',[block('Archetypes','Проникновение (Infiltration), Разведка (Recon).','Infiltration, Recon.'),block('Operatives','1 Техноархеолог (TECHNOARCHEOLOGIST).\n1 Сервитор-поднадзиратель (SERVITOR UNDERSEER).\nЕщё 8 оперативников: Автопрокси-сервитор (AUTO-PROXY SERVITOR); Сервитор-проломщик (BREACHER SERVITOR); Боевой сервитор (COMBAT SERVITOR) с сервоклешнёй и инцендиновым воспламенителем, мелтаганом либо фосфорным бластером; Стрелковый сервитор (GUN SERVITOR) с аугметической клешнёй и тяжёлой дуговой винтовкой либо тяжёлым болтером; Сервитор-техномедик (TECHNOMEDIC SERVITOR).',' '.join(s['teamSelection']['text'])),block('Selection restrictions','Каждый вариант из списка можно включить лишь один раз, кроме Боевых сервиторов (COMBAT SERVITOR). Можно выбрать не больше одного Боевого сервитора с мелтаганом и не больше трёх с инцендиновыми воспламенителями.','Other than COMBAT SERVITOR operatives each option can only be included once. Up to one COMBAT SERVITOR with meltagun and up to three with incendine igniter.')])
add('Noospheric Network','Ноосферическая сеть','FACTION RULE',[block('Transfer Power','Один раз в активацию каждого дружественного Сервитора Боевой клады (BATTLECLADE SERVITOR), до или после выполнения им действия, можно потратить 1 AP на передачу энергии (TRANSFER POWER). После той активации один другой дружественный Сервитор выполняет Сетевое контрдействие (NETWORK COUNTERACT) до активации противника.','Once during each friendly BATTLECLADE SERVITOR’s activation, before or after an action, spend 1AP to TRANSFER POWER. After that activation NETWORK COUNTERACT with one other friendly SERVITOR before your opponent activates.'),block('Network Counteract','Сначала выберите приказ оперативника. Затем он бесплатно выполняет действие стоимостью 1 AP, перемещаясь во время него не дальше 2 дюймов. После этого противник активирует оперативника как обычно.\nОперативник с APL меньше 2 не может передавать энергию или выполнять Сетевое контрдействие. NETWORK COUNTERACT считается контрдействием, но для него не требуется состояние «Использован» (Expended) или приказ «Бой» (Engage). Готовый (Ready) оперативник после этого может активироваться обычным образом в том же раунде. Выполнив NETWORK COUNTERACT, оперативник в этом раунде больше не может выполнить его или обычное контрдействие.','Whenever you NETWORK COUNTERACT first select the order, then perform a free 1AP action with movement capped at 2". The opponent then activates normally. APL less than 2 prevents TRANSFER POWER and NETWORK COUNTERACT. It is a counteraction but does not require expended or Engage; a ready operative can activate later. It cannot NETWORK COUNTERACT again or counteract in the same turning point.')])
for category,key in [('STRATEGY PLOY','strategyPloys'),('FIREFIGHT PLOY','firefightPloys'),('FACTION EQUIPMENT','factionEquipment')]:
 for x in s[key]:add(x['name'],names[x['name']],category,[block(x['name'],texts[x['name']],x['text'])])
melee={'Servo-arc claw','Taser goad','Hydraulic pincer & lascutter','Servo-claw','Augmetic claw','Dataspikes','Servo-chirurgic claw'}
for x in s['operatives']:
 ws=[{'type':'M'if w['name']in melee else'R','english':w['name'],'russian':weaponNames[w['name']],'atk':w['ATK'],'hit':w['HIT'],'dmg':w['DMG'],'wrEnglish':w['rules']if w['rules']!='-'else'','wrRussian':wr(w['rules'])}for w in x['weapons']]
 bs=[block(y['name'],texts[y['name']],y['text'],y.get('AP'))for y in x['abilities']]
 add(x['name'],names[x['name']],'OPERATIVE',bs,x['stats'],ws,x['keywordsAndBase'])
faqs=[
('System Exorcism: interruption','Можно ли остановить правилом «Изгнание из системы» (System Exorcism) запрет или прерывание активации? Да. Уловка применяется в любой момент разрешения «собираетесь активировать», включая момент до прерывания либо после уловок перестрелки; она имеет приоритет над такими правилами, и решение принимает игрок с инициативой.'),
('Remote Access: placing markers','Позволяет ли «Удалённый доступ» (Remote Access) РАЗМЕСТИТЬ маркер в пределах 4 дюймов вместо своей дистанции контроля? Нет.'),
('Network Counteract: no ready enemies','Можно ли выполнять NETWORK COUNTERACT, если у противника не осталось готовых оперативников для активации? Да.'),
('Network Counteract and Guard','Может ли оперативник, выполнивший контрдействие по Ноосферической сети, позже в этом раунде в свою активацию встать на «Дозор» (Guard)? Нет.'),
('System Exorcism: area effects','Как «Изгнание из системы» действует на эффекты, применяющиеся только пока оперативник находится в определённой области, например «Газовый обстрел» (Gas Bombardment)? В таких случаях уловка не имеет эффекта.'),
('System Exorcism: repeated tokens','Если эффект допускает несколько одинаковых жетонов на оперативнике, «Изгнание из системы» убирает один из них или все? Все жетоны этого эффекта.')]
for i in range(2):add('Battleclade Rules Commentary '+str(i+1),'Боевая клада · разъяснения '+str(i+1),'RULES COMMENTARY',[block(n,ru,s['faqs'][j]['q']+' '+s['faqs'][j]['a'])for j,(n,ru)in enumerate(faqs)if j//3==i])
add('Battleclade Marker and Token Guide','Боевая клада · жетоны и маркеры','TOKEN GUIDE',[block('Markers and tokens','Омнисканер (Omniscanner) · Приоритетное приобретение (Prioritised Acquisition) · Взор Омниссии (Gaze of the Omnissiah) · Механошовная система (Mechanosuture Array) · Сетевое контрдействие (Network Counteract) · Пролом (Breach).','; '.join(s['markerTokenGuide']['items']))])
for n,data in [('ru-images-supplement.json',cards),('inventory/image-sources.json',sources),('inventory/card-assets.json',assets),('inventory/supplement-card-manifest.json',manifest)]:
 (R/n).write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
print(json.dumps({'newCards':len(cards),'team':'Battleclade'}))
