"""Root current-rule corrections from full official/Waha audit E."""
import json,re
from pathlib import Path
R=Path(__file__).parent
def read(n):return json.loads((R/n).read_text(encoding='utf8'))
a=read('inventory/critic-full-team-audit-e.json');q=a['findings'];c=read('inventory/current-rule-base-cards.json');sources={x['team']:x for x in a['sources']};out=[]
def patch(n,id=None):
 x=q[n];id=id or x['exactID'];s=sources[x['team']]
 p={'id':id,'expectedTitle':c[id]['titleEnglish'],'team':x['team'],'source':{'officialPdf':s['officialPdfUrl'],'date':s['catalogDate'],'wahapedia':s['wahapediaPage'],'checkedOn':'2026-10-05',**x['officialEvidence']}};out.append(p);return p
def old(n,h=None):return next(b for b in c[q[n]['exactID']].get('blocks',[]) if h is None or b.get('headingEnglish')==h)
def body(n,ru,en,h=None):
 b=old(n,h);p=patch(n);u={'heading':b['headingEnglish'],'russian':ru,'english':en,'proseTitles':[b['headingEnglish'].split(' ·')[0].split(' (')[0].split(' —')[0].split(':')[0]]};p['blocks']=[u];return u
def edit(n,ro,rn,eo,en,h=None):
 b=old(n,h);assert ro in b['russian'] and eo in b['english'],(n,ro,eo)
 return body(n,b['russian'].replace(ro,rn),b['english'].replace(eo,en),h)
def extra(n,ru,en,h=None):
 b=old(n,h);return body(n,b['russian']+'\n'+ru,b['english']+' '+en,h)
def weapon(n,name,**values):patch(n)['weapons']=[{'name':name,**values}]
extra(0,'Во время одного контрдействия нельзя совместить «Ближний бой» (Fight) и «Стрельбу» (Shoot). Если при двойной «Стрельбе» хотя бы для одного действия выбрана мелта-бомба (Melta bomb), второе действие также требует дополнительный 1 AP.','You cannot perform both Fight and Shoot during that counteraction. If a melta bomb is selected for either of two Shoot actions, the second action also requires 1 additional AP.')
edit(1,'«Бронебойное 1» (Piercing 1)','«Бронебойное при критических успехах 1» (Piercing Crits 1)','; Piercing 1;','; Piercing Crits 1;')
edit(2,'или сражается с ним в ближнем бою','сражается с ним либо отвечает ему в ближнем бою','shooting or fighting against','shooting against, fighting against or retaliating against')
edit(3,'или сражается с ним в ближнем бою','сражается с ним либо отвечает ему в ближнем бою','shooting or fighting against','shooting against, fighting against or retaliating against')
body(4,'Когда дружественный оперативник Дозора Смерти (DEATHWATCH) целиком находится на территории противника, обычный урон (Normal Dmg) величиной 4 или выше, нанесённый ему, уменьшается на 1.','Whenever a friendly DEATHWATCH operative is wholly within your opponent’s territory, Normal Dmg of 4 or more inflicted on it is reduced by 1.')
edit(5,'на вашей территории','целиком на вашей территории','in your territory','wholly within your territory')
body(6,'Когда этот оперативник сражается или отвечает в ближнем бою, уменьшите на 1 обычный и критический урон (Normal/Critical Dmg) величиной 3 или выше, нанесённый ему. Это не складывается с «Щитом, который убивает» (The Shield That Slays).','Whenever this operative is fighting or retaliating, Normal and Critical Dmg of 3 or more inflicted on it is reduced by 1. This is not cumulative with The Shield That Slays.',h='Aggressive Force')
extra(7,'Последующие действия «Стрельба» (Shoot) в этой активации или контрдействии тоже должны удовлетворять этим условиям; иначе уловка не действует для них.','Subsequent Shoot actions during that activation or counteraction must also meet these requirements or the ploy has no effect for them.',h='Auspex Triangulation')
edit(8,'Вместо обычного успеха сохраните один свой критический успех.','Сохраните один свой обычный успех как критический.','Retain one of your normal successes as a critical success instead.','Retain one of your normal successes as a critical success instead.')
edit(9,'видимого ему','находящегося в зоне боя','visible to it','in the killzone',h='Guidance and Experience')
edit(10,'из тяжёлого болтера или ракетной установки','из любого оружия на своей карточке','with a heavy bolter or missile launcher','with any weapon on its datacard')
body(12,'Выберите до D3 дружественных Разведчиков (SCOUT SQUAD) с приказом «Скрытность» (Conceal), находящихся дальше 4 дюймов от врагов. Они немедленно бесплатно выполняют «Рывок» (Dash) в выбранном вами порядке. Нельзя применять эту уловку в первом раунде.','Select up to D3 friendly SCOUT SQUAD operatives with a Conceal order more than 4" from enemy operatives. They can immediately perform a free Dash in your chosen order. You cannot use this ploy during the first turning point.')
for n in [13,14]:weapon(n,'Combat blade',dmg='4/5')
u=edit(15,'действие «Рывок» (Dash) или «Отступление» (Fall Back)','действие «Отступление» (Fall Back)','a free Dash or Fall Back action','a free Fall Back action');u['russian']=u['russian'].replace('после удара критическим успехом.','после удара критическим успехом, если враг ещё не выведен из строя.').replace('«Рывок» или «Отступление»','«Отступление»');u['english']=u['english'].replace('after you strike with a critical success.','after you strike with a critical success if the enemy is not incapacitated.').replace('performing Dash or Fall Back','performing Fall Back')
edit(17,'в ближнем бою или отвечая на атаку','сражаясь в ближнем бою','while fighting or retaliating','while fighting',h='Epic')
extra(17,'Акколада применяется только когда этот оперативник сражается в ближнем бою.','The Accolade applies while the operative is fighting.',h='Epic')
w=next(w for w in c[q[18]['exactID']]['weapons'] if 'Hallucinogen' in w['english']);weapon(18,w['english'],wrEnglish=w['wrEnglish']+', Seek Light',wrRussian=w['wrRussian']+', Обнаружение в лёгком укрытии (Seek Light)')
for n in [19,20]:weapon(n,'Blade',dmg='4/6')
edit(21,'«Непрерывное» (Ceaseless); если оружие уже имеет его','«Сбалансированное» (Balanced); если оружие уже имеет его','have Ceaseless; if a weapon already has Ceaseless','have Balanced; if a weapon already has Balanced')
edit(22,'участвует в ближнем бою','сражается либо отвечает в ближнем бою','is fighting,','is fighting or retaliating,')
extra(23,'В обоих случаях итоговый урон не может превышать 7.','Both additional damage and both Khorne melee damage stats are capped at 7.')
extra(24,'В эту активацию выбранный оперативник не может выполнить одно и то же действие больше одного раза.','That operative cannot perform the same action more than once during that activation.')
edit(25,'видимого этому бойцу и находящегося от него не дальше 6 дюймов','находящегося в пределах 6 дюймов от этого бойца','visible to and within 6" of this operative','within 6" of this operative')
edit(26,'до двух допустимых целей','до двух разных допустимых целей вне дистанции контроля дружественных оперативников','up to two valid targets','up to two different valid targets that aren’t within control range of friendly operatives',h='Salvo*')
extra(27,'Если цель выведена из строя во время действия, нацеленного на нескольких оперативников, выберите новую цель в конце этого действия после удаления выведенных из строя оперативников.','If the mark is incapacitated during an action targeting multiple operatives, select the replacement mark at the end of that action after incapacitated operatives are removed.',h='Call the Kill — Strategic Gambit')
for n in range(28,37):
 matches=[w for w in c[q[n]['exactID']]['weapons'] if 'blade' in w['english'].lower() or n==32 and 'pistols' in w['english'].lower()]
 assert matches,n
 p=patch(n);p['weapons']=[{'name':w['english'],'dmg':'3/5'} for w in matches]
u=edit(37,'Правила могут совпадать','Нельзя выбрать одно и то же правило для обоих','they can be the same','they cannot be the same');u.update(newHeadingEnglish='Inquisitorial Tomes: STRATEGIC GAMBIT',headingRussian='Фолианты Инквизиции · стратегический гамбит (Inquisitorial Tomes)');u['russian']='СТРАТЕГИЧЕСКИЙ ГАМБИТ (STRATEGIC GAMBIT), если этот оперативник находится в зоне боя. '+u['russian'];u['english']='STRATEGIC GAMBIT if this operative is in the killzone. '+u['english']
edit(40,', видимого дружественному оперативнику Кровавых','', ' visible to a friendly BLOODED operative','')
edit(41,'жетон и он полностью','жетон либо он целиком','Blooded tokens and is wholly','Blooded tokens or is wholly',h='Lead With Strength')
body(42,'Когда дружественный Кровавый (BLOODED) активируется в пределах 6 дюймов от этого оперативника, можно игнорировать изменения его характеристик из-за ранения (Injured), включая характеристики оружия, до конца той активации.','Whenever a friendly BLOODED operative is activated within 6" of this operative, you can ignore changes to its stats from being injured (including weapon stats) until the end of that activation.',h='Gruelling Disciplinarian')
body(43,'При следующей «Атаке» (Charge) в эту активацию добавьте 4 дюйма к допустимой дистанции перемещения вместо обычных 2 дюймов. Нельзя выполнять это действие больше одного раза за бой либо в первом раунде.','The next Charge action during this activation adds 4" to movement instead of the normal 2". This operative cannot perform this action more than once per battle or during the first turning point.',h='Boost (1AP)')
extra(44,'На тот же срок это оружие получает «Точное 1» (Accurate 1).','That weapon also has Accurate 1 until the end of that action.')
w=next(w for w in c[q[45]['exactID']]['weapons'] if 'detonator' in w['english'].lower());weapon(45,w['english'],wrEnglish=w['wrEnglish'].replace('Lethal 5+','Lethal 4+'),wrRussian=w['wrRussian'].replace('5+','4+'))
for n in range(46,57):patch(n)['stats']={'Wounds':int(q[n]['currentfullrule'].split()[-1].strip('.'))}
body(57,'Примените эту уловку перестрелки (FIREFIGHT PLOY) во время активации дружественного Абордажника Имперского флота (IMPERIAL NAVY BREACHER). В эту активацию он может пройти через один элемент доступного террейна (Accessible) без дополнительного дюйма перемещения и/или бесплатно выполнить «Управлять люком» (Operate Hatch), в том числе во время «Атаки» (Charge) или «Отступления» (Fall Back). Нельзя применять к заваренной точке доступа, кроме активации дружественного Резчика люков (HATCHCUTTER).','Use this firefight ploy during a friendly IMPERIAL NAVY BREACHER operative’s activation. It can move through one Accessible terrain feature without the additional inch and/or perform a free Operate Hatch during that activation, including during Charge or Fall Back. Cannot use if the access point is welded shut unless it is a friendly HATCHCUTTER operative’s activation.')
body(58,'Примените эту уловку перестрелки (FIREFIGHT PLOY), активируя любого из двух дружественных Абордажников Имперского флота (IMPERIAL NAVY BREACHER) по правилу «Прорыв и зачистка» (Breach and Clear). До конца этой активации увеличьте APL активированного оперативника на 1.','Use this firefight ploy when activating either friendly IMPERIAL NAVY BREACHER operative while using Breach and Clear. Add 1 to that activated operative’s APL until the end of its activation.')
body(59,'Когда дружественный Абордажник Имперского флота (IMPERIAL NAVY BREACHER) сражается либо стреляет по оперативнику в пределах 3 дюймов, увеличьте обе характеристики DMG его навийского дробовика (Navis shotgun) и тяжёлого дробовика (Navis heavy shotgun) на 1. Если вы бросили хотя бы два провала, можно сбросить один из них, чтобы сохранить другой как обычный успех.','Whenever a friendly IMPERIAL NAVY BREACHER operative is fighting or shooting an operative within 3", add 1 to both Dmg stats of its navis shotgun and navis heavy shotgun. If you roll at least two fails, you can discard one to retain another as a normal success.')
patch(60)['stats']={'Save':'3+'}
edit(61,'число атак 6','ATK 5','ATK 6','ATK 5');weapon(61,'Shriek-that-kills',atk=5)
edit(62,'по оперативнику не в укрытии','по оперативнику вне укрытия и дальше 6 дюймов от него','against an operative that isn’t in cover','against an operative more than 6" away that isn’t in cover')
for n in [63,64]:edit(n,'оперативник карабкается','оперативник карабкается вверх','operative is climbing,','operative is climbing up,')
for n,faction,ruFaction in [(39,'INQUISITORIAL AGENT','Агентов Инквизиции (INQUISITORIAL AGENT)'),(65,'PHOBOS STRIKE TEAM','Ударного отряда Фобос (PHOBOS STRIKE TEAM)')]:
 medic=c['7b57d5bb83d8aba7']['blocks'][0];body(n,medic['russian'].replace('DEATH KORPS',ruFaction),medic['english'].replace('DEATH KORPS',faction),h='Medic!')
extra(66,'В зонах боя с правилами тесного боя (Close Quarters) оружие детонации (Detonate) получает «Смертоносное 5+» (Lethal 5+).','In close-quarters killzones the Detonate weapon gains Lethal 5+.',h='Plant Explosives')
body(68,'Первый раз за раунд, когда другой дружественный Элюцидийский звёздостранник (ELUCIDIAN STARSTRIDER), видимый этому оперативнику и в пределах 3 дюймов, должен быть выведен из строя, можно применить это правило, если ни один из них не находится в дистанции контроля врага. Союзник не выводится из строя: у него остаётся 3 раны и его нельзя вывести из строя до конца текущего действия. После этого действия он может немедленно бесплатно выполнить «Рывок» (Dash), закончив его в дистанции контроля медика. Если правило применено в активацию спасённого союзника, она заканчивается. Нельзя применять правило, если медик выведен из строя либо если это «Стрельба» (Shoot), при которой медик становится основной или вторичной целью.','The first time each turning point that another friendly ELUCIDIAN STARSTRIDER would be incapacitated while visible to and within 3" of this operative, you can use this rule providing neither is within enemy control range. It is not incapacitated, has 3 wounds remaining and cannot be incapacitated for the remainder of the action. After that action it can immediately perform a free Dash ending within this operative’s control range. If used during that friendly operative’s activation, that activation ends. Cannot use if this operative is incapacitated or if it is a Shoot action and this operative would be a primary or secondary target.',h='Medic!')
extra(38,'Эффект действует только пока этот оперативник находится в зоне боя.','This effect only applies if this operative is in the killzone.',h='Scrivener')
body(67,'Примените эту уловку перестрелки (FIREFIGHT PLOY), когда активируется дружественный Элюцидийский звёздостранник (ELUCIDIAN STARSTRIDER). Он восстанавливает до D3+2 потерянных ран. До конца этой активации можно игнорировать любые изменения его APL.','Use this firefight ploy when a friendly ELUCIDIAN STARSTRIDER operative is activated. It regains up to D3+2 lost wounds and during that activation you can ignore any changes to its APL stat.')
edit(69,'До трёх раз','До четырёх раз','Up to three times','Up to four times',h='Rule')
edit(70,'до четырёх применений','до пяти применений','up to four uses per battle instead of three','up to five uses per battle instead of four',h='Reputation to Maintain')
body(71,'Когда: в начале шага выставления оперативников (Set Up Operatives). Противник выставляет всех своих оперативников до вас. Также выберите один вариант: противник выставляет всё своё снаряжение до вашего; либо вы выставляете всё своё снаряжение до противника.','When: At the start of Set Up Operatives. Your opponent sets up all their operatives before you set up any. Also select one: your opponent sets up all their equipment before you set up any; or you set up all your equipment before your opponent sets up any.',h='Coerce')
edit(72,'один дружественный оперативник отряда, целиком находящийся в зоне высадки, бесплатно выполняет действие','D3 дружественных оперативника отряда, целиком находящихся в зоне высадки, бесплатно выполняют действие','with one friendly ELUCIDIAN STARSTRIDER operative','with D3 friendly ELUCIDIAN STARSTRIDER operatives',h='Explore');u=out[-1]['blocks'][0];u['russian']=u['russian'].replace('Он должен закончить перемещение целиком в пределах 3 дюймов','Каждый должен закончить перемещение целиком в пределах 4 дюймов');u['english']=u['english'].replace('It must end that move wholly within 3″','Each must end that move wholly within 4″')
u=edit(73,'лазпистолет или лазган','лазпистолет, лазган или реликтовый лазпистолет','a laspistol or lasgun','a laspistol, lasgun or relic laspistol');u['russian']=u['russian'].replace(' Реликтовые лазпистолеты не подходят.','');u['english']=u['english'].replace(' Relic laspistols are excluded.','')
body(74,'Разместите маркер Притязаний (Claim) в зоне боя. Когда дружественный Элюцидийский звёздостранник (ELUCIDIAN STARSTRIDER) стреляет по врагу, сражается с ним либо отвечает ему в ближнем бою, если враг в пределах 3 дюймов от маркера, на шаге броска кубиков атаки можно сохранить один провал как обычный успех вместо сброса либо один обычный успех как критический. Удалите маркер в конце раунда.','Place your Claim marker in the killzone. Whenever a friendly ELUCIDIAN STARSTRIDER is shooting against, fighting against or retaliating against an enemy within 3" of it, in the Roll Attack Dice step you can retain a fail as a normal success instead of discarding it or a normal success as a critical. Remove the marker at the end of the turning point.')
extra(75,'Также игнорируйте эффекты вражеского оружия с «Потрясением» (Shock).','Also ignore enemy Shock effects.',h='3. Resolute')
extra(76,'На тот же срок это оружие также получает «Точное 1» (Accurate 1).','The bolt weapons also have Accurate 1 for the same duration.',h='7. Sharpshooter')
extra(76,'Когда этот оперативник сражается либо отвечает в ближнем бою, враги не могут получать помощь (Assistance).','Whenever this operative is fighting or retaliating, enemy operatives cannot assist.',h='8. Siege Specialist')
extra(78,'Варианты Доктрины опустошителя (Devastator) и Тактической доктрины (Tactical) можно применить каждый по одному разу за бой.','The Devastator and Tactical options can each be used once per battle.',h='Doctrine Warfare')
edit(77,'после броска атакующих кубиков противника','после броска атакующих кубиков противника, но до перебросков','after your opponent rolls attack dice,','after your opponent rolls attack dice, but before re-rolls,')
body(79,'Один раз за раунд выберите один вариант:\n• Применить уловку перестрелки за 0 CP, если она требует именно этого Ангела Смерти (ANGEL OF DEATH), кроме «Командного переброса» (Command Re-roll).\n• Применить стратегическую уловку «Боевая доктрина» (Combat Doctrine) при активации дружественного Ангела Смерти, если этот оперативник находится в зоне боя и вне дистанции контроля врагов. Оплатите CP как обычно; нельзя сделать это, если в этом раунде вы уже применяли эту уловку.\n• Применить «Сменить доктрину» (Adjust Doctrine) за 0 CP, если этот оперативник находится в зоне боя и вне дистанции контроля врагов.','Once per turning point choose one: use a firefight ploy for 0CP if this is the specified ANGEL OF DEATH operative (excluding Command Re-roll); use Combat Doctrine when activating a friendly ANGEL OF DEATH operative if this operative is in the killzone and outside enemy control range, paying its normal CP cost and not if that ploy was already used this turning point; or use Adjust Doctrine for 0CP if this operative is in the killzone and outside enemy control range.',h='Heroic Leader')
weapon(80,'Bolt pistol',append=True,type='R',russian='Болт-пистолет (Bolt pistol)',atk=4,hit='3+',dmg='3/4',wrEnglish='Range 8"',wrRussian='Дальность 8" (Range 8")')
edit(81,' Нельзя вместе выбрать более одного из снайпера элиминаторов и тяжёлого стрелка интерцессоров.','',' You cannot select more than one ELIMINATOR SNIPER and HEAVY INTERCESSOR GUNNER combined.','')
out[-1]['blocks'][0]['english']=out[-1]['blocks'][0]['english'].replace('ELIMINATOR SNIPER*','ELIMINATOR SNIPER').replace('HEAVY INTERCESSOR GUNNER*','HEAVY INTERCESSOR GUNNER')
for p in out:
 for u in p.get('blocks',[]):u['russian']=re.sub(r'\b(?:ОД|ОК)\b',lambda m:'AP' if m[0]=='ОД' else 'CP',u['russian'])
(R/'ru-current-updates-e.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf8');print(json.dumps({'patches':len(out),'pending':[11,16,38,67,68,77,79]}))
