"""Root-authored effective-body corrections; struck errata text is excluded."""
import json,re
from pathlib import Path
R=Path(__file__).parent
def read(n):return json.loads((R/n).read_text(encoding='utf8'))
a=read('inventory/current-team-audit-c-stable.json');q=a['queue'];c=read('inventory/current-rule-base-cards.json');out=[]
def body(n,h,ru,en=None,id=None,append=False,hr=None):
 x=q[n];id=id or x['localIds'][0];s=a['sources']['teams'][x['team']]
 old=next((b for b in c[id].get('blocks',[]) if b.get('headingEnglish')==h),None)
 assert old or append,(id,h)
 if en is None:en=x.get('currentFullEnglish');assert en,(n,'full English missing')
 u={'heading':h,'russian':ru,'english':en,'proseTitles':[h.split(' ·')[0].split(' (')[0].split(':')[0]]}
 if append:u.update(append=True,headingRussian=hr or h)
 out.append({'id':id,'expectedTitle':c[id]['titleEnglish'],'team':x['team'],'source':{'officialPdf':s['officialPdf'],'date':s['officialCatalogLastUpdated'],'wahapedia':s['wahapedia'],'checkedOn':'2026-10-05',**x['source']},'blocks':[u]});return u
def edit(n,h,ro,rn,eo,en,id=None):
 b=next(b for b in c[id or q[n]['localIds'][0]].get('blocks',[]) if b.get('headingEnglish')==h)
 assert ro in b['russian'] and eo in b['english'],(n,h,ro,eo)
 return body(n,h,b['russian'].replace(ro,rn),b['english'].replace(eo,en),id=id)
def extra(n,h,ru,en):
 b=next(b for b in c[q[n]['localIds'][0]]['blocks'] if b.get('headingEnglish')==h);return body(n,h,b['russian']+'\n'+ru,b['english']+' '+en)
body(39,'Operatives','1 Темпестор (TEMPESTUS AQUILON TEMPESTOR): лазпистоль повышенной мощности и силовое оружие; реликтовый болт-пистолет и цепной меч; либо лазкарабин повышенной мощности и кулаки.\n1 Серво-часовой (SERVO-SENTRY) с огнемётом, гранатомётом либо залповым лазганом повышенной мощности.\nЕщё 9 Аквилонов Темпестус (TEMPESTUS AQUILON): Гренадёр (GRENADIER), Пистолетчик (GUNFIGHTER), Стрелок (GUNNER) с мелта-карабином и кулаками, Стрелок с плазмакарабином и кулаками, Снайпер (MARKSMAN), Предтеча (PRECURSOR), Рядовой (TROOPER).','1 TEMPESTUS AQUILON TEMPESTOR with hot-shot laspistol and power weapon, relic bolt pistol and chainsword, or hot-shot lascarbine and fists. 1 TEMPESTUS AQUILON SERVO-SENTRY with flamer, grenade launcher or hot-shot volley gun. 9 TEMPESTUS AQUILON operatives: GRENADIER, GUNFIGHTER, GUNNER with melta carbine and fists, GUNNER with plasma carbine and fists, MARKSMAN, PRECURSOR, TROOPER.')
body(39,'Selection restrictions','Кроме Рядовых (TROOPER), в отряд можно включить каждый вариант оперативника из этого списка только один раз.','Other than TROOPER operatives, your kill team can only include each operative on this list once.',id=q[39]['localIds'][1])
body(39,'Operatives · continuation','Серво-часовой (SERVO-SENTRY) выбирается отдельно: он входит в отряд дополнительно к Темпестору и девяти остальным Аквилонам.','The SERVO-SENTRY is selected separately in addition to the TEMPESTOR and nine other operatives.',id=q[39]['localIds'][1])
edit(40,'Dynamic',', но тогда для рывка доступна только неиспользованная дистанция этой атаки, не более 3 дюймов','',', but can only use the remaining distance it had from that Charge action (to a maximum of 3 inches)','')
body(41,'Hot Drop','Примените эту уловку перестрелки (FIREFIGHT PLOY) после броска кубиков атаки дружественного Аквилона Темпестус (TEMPESTUS AQUILON), если он целиком находится на территории противника либо в эту активацию десантировался или спрыгнул с высоты (Vantage), расположенной хотя бы на 2 дюйма выше пола зоны боя. Если цель находится в пределах 6 дюймов от него, можно перебросить любые свои кубики атаки.','Use this firefight ploy after rolling attack dice for a friendly TEMPESTUS AQUILON operative wholly within your opponent’s territory or that landed or dropped from Vantage terrain at least 2" above the killzone floor during this activation. If the target is within 6" of it, you can re-roll any of your attack dice.')
edit(42,'Salvo','до двух допустимых целей','до двух разных допустимых целей вне дистанции контроля дружественных оперативников','up to two valid targets','up to two different valid targets that aren’t within control range of friendly operatives')
extra(44,'Gunfight','Если противник не сбросил ни одного кубика как провал, ответная «Стрельба» (Shoot) всё равно разрешена: бросьте один кубик атаки.','This operative can shoot back with one attack die even if no enemy attack dice were discarded as failures.')
edit(47,'Fate Itself is my Weapon','нельзя изменить или перебросить, и его сбрасывают','нельзя изменить, перебросить или сохранить как обычный либо критический успех, если он им не является; его сбрасывают','cannot be changed or re-rolled and is discarded','cannot be changed, re-rolled or retained as a normal or critical success if it is not one and is discarded')
for n,h in [(48,'Sorcerous Scrolls'),(49,'Arcane Robes')]:
 b=next(b for b in c[q[n]['localIds'][0]]['blocks'] if b.get('headingEnglish')==h);body(n,h,b['russian'],b['english']) # Precedence/per-Sorcerer additions are struck out.
edit(55,'Spot · 1AP','Один раз за раунд, когда','До конца раунда каждый раз, когда','Once during this turning point, when','Until the end of the turning point, whenever')
body(56,'Early Warning','Один раз за раунд после того, как враг выполнит действие с перемещением или выставлением заново, можно прервать ход игры и применить это правило. Каждый дружественный Ратлинг (RATLING), кроме Огрина (OGRYN) и Булгрина (BULLGRYN), находящийся в пределах 6 дюймов от этого Боевого пса и в пределах 2 дюймов от переместившегося врага, может немедленно бесплатно выполнить «Рывок» (Dash) или «Отступление» (Fall Back). Выбирайте действие отдельно для каждого и порядок их действий. За это действие нельзя переместиться дальше 3 дюймов. В обоих случаях нельзя закончить перемещение в пределах 2 дюймов от врага, если только в конце перемещения оперативник не виден ни одному врагу. Если последнее условие невозможно выполнить, оперативник не перемещается.','Once per turning point, after an enemy operative performs an action in which it moves or is set up, you can interrupt and use this rule. Each friendly RATLING operative excluding OGRYN and BULLGRYN within 6" of this operative and within 2" of that enemy can immediately perform a free Dash or Fall Back in your chosen order (choose separately for each), but cannot move more than 3". They cannot end within 2" of an enemy operative unless not visible to every enemy operative when they end; if this is not possible, they do not move.')
edit(57,'Tripwire','дальше 2 дюймов от других маркеров','дальше 2 дюймов от других маркеров, точек доступа (Access Points) и доступного террейна (Accessible)','more than 2" from other markers','more than 2" from other markers, access points and Accessible terrain')
edit(58,'Grappling Hook','оперативник карабкается','оперативник карабкается вверх','this operative is climbing','this operative is climbing up')
body(59,'Slingshot · 1AP','Выберите точку на террейне, видимую этому оперативнику и в пределах 6 дюймов от него. Уберите его из зоны боя и выставьте заново целиком в пределах 6 дюймов по горизонтали от выбранной точки, вне дистанции контроля врагов и так, чтобы точка была ему видна. Это действие считается «Перемещением» (Reposition). Его нельзя выполнять в дистанции контроля врага или в активацию, в которой оперативник выполнял «Атаку» (Charge), «Отступление» (Fall Back) или «Стрельбу» (Shoot), и наоборот.','Select a point on terrain visible to and within 6" of this operative. Remove this operative from the killzone and set it up wholly within 6" horizontally of that point, outside enemy control range and with that point visible. Treat this as Reposition. This operative cannot perform this action while within enemy control range, or during an activation in which it performs Charge, Fall Back or Shoot (or vice versa).')
body(59,'Slingshot diagram','Выберите видимую точку в пределах 6 дюймов. Повторное выставление: целиком в пределах 6 дюймов по горизонтали от неё.','Choose a visible point within 6"; set up wholly within 6" horizontally of it.')
extra(60,'Optics · 1AP','На тот же срок неподвижный профиль снайперской винтовки с глушителем (Suppressed sniper rifle, stationary) получает «Смертоносное 5+» (Lethal 5+).','Until the same time, its suppressed sniper rifle (stationary) has Lethal 5+.')
edit(60,'Evade','прервать его активацию или контрдействие','прервать ход игры','interrupt that activation/counteraction','interrupt')
edit(61,'Sniper Positions','в его дистанции контроля есть тяжёлый террейн (Heavy terrain)','он находится в пределах 1 дюйма от тяжёлого террейна (Heavy terrain)','has Heavy terrain within its control range','is within 1" of Heavy terrain')
edit(62,'Scarper',' Нельзя применять это правило после двух активаций вражеских оперативников подряд в одном раунде: после применения пропустите следующую возможность и только после этого снова сможете его использовать.','',' You cannot use this rule after consecutive enemy activations during the same turning point (in other words, after using this rule, you must skip the next opportunity during that turning point before you can use it again).','')
edit(63,'Lucky Round',', если в этой активации вы не использовали снаряжение «Похищенный паёк» (Purloined Rations)',''," if you haven’t used the Purloined Rations equipment this activation",'')
body(64,'Purloined Rations','Один раз за раунд после броска кубиков атаки дружественного Ратлинга (RATLING), стреляющего из винтовки, можно применить это правило. До конца этой последовательности улучшите HIT этого оружия на 1. Это правило имеет приоритет над обычным запретом изменять характеристики оружия во время действия.','Once per turning point, after rolling attack dice for a friendly RATLING operative shooting with a rifle, you can use this rule. Improve that weapon’s Hit by 1 until the end of that sequence. This takes precedence over the normal rule that weapon stats cannot be changed during an action.')
body(72,'Auspex Scan','1 AP. До начала следующей активации этого оперативника либо его выведения из строя, что наступит раньше, все враги в пределах 8 дюймов от него считаются Просканированными (Scanned). Когда дружественный Касркин (KASRKIN) стреляет по Просканированному врагу, тот не может считаться заслонённым (Obscured). Нельзя выполнять это действие в дистанции контроля врага.','1AP. Until the start of this operative’s next activation or until it is incapacitated (whichever comes first), enemy operatives within 8" of this operative are Scanned. Whenever a friendly KASRKIN operative shoots a Scanned enemy, that enemy cannot be obscured. This operative cannot perform this action within enemy control range.')
body(73,'Veteran Leadership','Когда применяется стратегический гамбит «Оружейное мастерство» (Skill at Arms), если этот оперативник находится в зоне боя, можно выбрать один дополнительный навык. Нельзя выбрать тот же навык дважды.','Whenever you use the Skill at Arms STRATEGIC GAMBIT, if this operative is in the killzone, you can select one additional Skill at Arms, but it cannot be one you have already selected.',append=True,hr='Опытный командир (Veteran Leadership)')
medic=c['7b57d5bb83d8aba7']['blocks'][0]
body(74,'Medic!',medic['russian'].replace('DEATH KORPS','Касркинов (KASRKIN)'),medic['english'].replace('DEATH KORPS','KASRKIN'))
body(75,'Rapid Fire','Если дружественный Касркин (KASRKIN) не перемещается в свою активацию, он может выполнить в ней два действия «Стрельба» (Shoot), кроме «Дозора» (Guard). Для обоих нужно использовать болт-пистолет, лазган повышенной мощности или лазпистоль повышенной мощности.','Whenever a friendly KASRKIN operative does not move during its activation, it can perform two Shoot actions during that activation (excluding Guard), but both must use a bolt pistol, hot-shot lasgun or hot-shot laspistol.',append=True,hr='Быстрый огонь (Rapid Fire)')
edit(76,'Ice in Your Veins','обычный урон 4 или более','обычный урон 3 или более','Normal Dmg 4 or more','Normal Dmg 3 or more')
extra(77,'For Cadia!','В каждой последовательности ближнего боя первый удар дружественного Касркина наносит на 1 урон больше.','In each Fight sequence, the first strike by a friendly KASRKIN operative inflicts 1 additional damage.')
body(78,'Light ’Em Up','Стрелковое оружие дружественных Касркинов (KASRKIN) получает «Сокрушительное» (Severe).','Friendly KASRKIN operatives’ ranged weapons have Severe.')
edit(79,'Clearance Sweep','«Сбалансированное» (Balanced)','«Непрерывное» (Ceaseless)','have Balanced','have Ceaseless')
edit(80,'Elimination Pattern','по цели без укрытия','по Просканированной (Scanned) цели либо цели, которая не может сохранять защиты от укрытия (Cover saves)','against a target not in cover','against a Scanned target or a target that cannot retain cover saves')
edit(81,'Neutralise Target','цель использованная (expended) и не находится в укрытии','цель Просканирована (Scanned) либо не может сохранять защиты от укрытия (Cover saves)','the target is expended and not in cover','the target is Scanned or cannot retain cover saves')
extra(82,'Cover Retreat','Для этой бесплатной «Стрельбы» он может изменить свой приказ на «Бой» (Engage).','It can change its order to Engage to perform that free Shoot action.')
edit(83,'Tactical Command','который будет действовать для него вместо текущего','который дополнительно действует для него вместе с имеющимися навыками; нельзя выбрать навык, который у него уже есть','for it to have (instead of any it currently has)','for it to have in addition to any it currently has; it cannot be a Skill it already has')
for p in out:
 for u in p['blocks']:u['russian']=re.sub(r'\bОД\b','AP',u['russian'])
(R/'ru-current-updates-c-rest.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
print(json.dumps({'fullBodyPatches':len(out),'pending':['Battleclade','full FAQs','Warpcoven roster']}))
